Use buildsystem info to get the ros_package_info
ros2/rviz pull request #1062
Opened 2023-09-11 11:05 UTC by ahcorde

Releted with this issue https://github.com/ros2/rviz/issues/47

2023-09-11 11:43 UTC, clalancette requested changes
Two minor things to fix, but this otherwise looks good to me!

2023-09-11 11:43 UTC, clalancette commented on rviz_rendering/CMakeLists.txt
> +find_package(ament_cmake_ros REQUIRED)
We don't typically need both `ament_cmake_ros` and `ament_cmake`; the former depends on the latter.

```suggestion
find_package(ament_cmake_ros REQUIRED)
```

2023-09-11 11:43 UTC, clalancette commented on rviz_rendering/package.xml
> +  <buildtool_depend>ament_cmake_ros</buildtool_depend>
Same here:

```suggestion
  <buildtool_depend>ament_cmake_ros</buildtool_depend>
```

2023-09-11 12:05 UTC, clalancette approved these changes
Looks good to me with green CI!  Make sure to run CI with `--packages-above-and-dependencies rviz_rendering`, just to make sure there is no downstream problem.

2023-09-11 12:33 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19489)](http://ci.ros2.org/job/ci_linux/19489/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14009)](http://ci.ros2.org/job/ci_linux-aarch64/14009/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20207)](http://ci.ros2.org/job/ci_windows/20207/)

2023-09-12 20:14 UTC, ahcorde commented
@clalancette the windows build is failing. I tried to reproduce this locally,

if I use `ament_cmake` and set manually `add_definitions(-DROS_PACKAGE_NAME=\"${PROJECT_NAME}\")` The compilation is fine, 

but with `ament_cmake_ros` I'm getting these errors:

```
16:28:24 LINK : fatal error LNK1181: cannot open input file 'Release\rviz_rendering_test_utils.lib' [C:\ci\ws\build\rviz_rendering\billboard_line_test_target.vcxproj]

16:28:24   Building Custom Rule C:/ci/ws/src/ros2/rviz/rviz_rendering/CMakeLists.txt

16:28:24   covariance_visual_test.cpp

16:28:24 LINK : fatal error LNK1181: cannot open input file 'Release\rviz_rendering_test_utils.lib' [C:\ci\ws\build\rviz_rendering\covariance_visual_test_target.vcxproj]

16:28:24   Building Custom Rule C:/ci/ws/src/ros2/rviz/rviz_rendering/CMakeLists.txt
```

any thoughts?

2023-09-12 20:27 UTC, clalancette commented
> any thoughts?

With `ament_cmake_ros`, the libraries should be getting built as shared objects by default.  What is weird about the above is it seems like `rviz_rendering_test_utils.lib` is getting built statically somehow (that should be a `.dll`).  I guess you could try explicitly adding the `SHARED` keyword to the `add_library(rviz_rendering_test_utils)` call, but it really should not be necessary.

2023-09-12 20:55 UTC, ahcorde commented
I think I solved with the visibility

* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20224)](http://ci.ros2.org/job/ci_windows/20224/)

2023-09-13 08:18 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19505)](http://ci.ros2.org/job/ci_linux/19505/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14025)](http://ci.ros2.org/job/ci_linux-aarch64/14025/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20226)](http://ci.ros2.org/job/ci_windows/20226/)

2023-09-13 13:55 UTC, clalancette requested changes
Two small nits, then this looks good to me.

2023-09-13 13:55 UTC, clalancette commented on rviz_rendering/CMakeLists.txt
> +  "TEST_RVIZ_RENDERING_BUILDING_LIBRARY")
```suggestion
    "TEST_RVIZ_RENDERING_BUILDING_LIBRARY")
```

2023-09-13 13:55 UTC, clalancette commented on rviz_rendering/CMakeLists.txt
> +  add_library(rviz_rendering_test_utils SHARED
```suggestion
  add_library(rviz_rendering_test_utils
```

(it's not necessary anymore since it is indeed the default for `ament_cmake_ros`)

2023-09-13 14:15 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19507)](http://ci.ros2.org/job/ci_linux/19507/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14027)](http://ci.ros2.org/job/ci_linux-aarch64/14027/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20228)](http://ci.ros2.org/job/ci_windows/20228/)

2023-09-13 14:15 UTC, clalancette approved these changes
Looks good with green CI.

2023-09-13 17:41 UTC, merged