Use assimp to load stl
ros2/rviz pull request #1063
Opened 2023-09-11 14:07 UTC by ahcorde

Related with this issue https://github.com/ros2/rviz/issues/712, this is the current behaviour of the ROS 1 version https://github.com/ros-visualization/rviz/pull/1365/files#diff-931ce7a05c370df33e2308f9adb590d3bde08241cf0e03dc86037731e3a5d83f

2023-09-13 19:32 UTC, clalancette reviewed
I only have one concern with this PR, which is whether all of the STL files we used to be able to load still load after this.  There are like 600 in the Rolling sources right now, which is obviously too many to test by hand.

I'm not quite sure how to test this; @ahcorde what's your feeling here?

2023-09-13 19:42 UTC, ahcorde commented
> I only have one concern with this PR, which is whether all of the STL files we used to be able to load still load after this. There are like 600 in the Rolling sources right now, which is obviously too many to test by hand.
> 
> I'm not quite sure how to test this; @ahcorde what's your feeling here?

This behaviour is already working on ROS 1. Just to avoid discrepancies between them when porting to ROS 2.

2023-10-06 08:15 UTC, ahcorde commented
friendly ping @clalancette

2023-10-09 20:30 UTC, clalancette requested changes
I've left a few minor comments on things to cleanup.

I have to say that while I think this is the correct thing to do, I'm a little nervous about it.  It seems like we'll be rejecting more STL files now.  But I guess the best we can do is try it out and see what happens.

2023-10-09 20:30 UTC, clalancette commented on rviz_rendering_tests/test/mesh_loader_test.cpp
>    /// ignored.
I think we should remove this comment now, right?  That is, we will *not* succeed on these STL files anymore, if I understand the change.

2023-10-09 20:30 UTC, clalancette commented on rviz_rendering_tests/test/mesh_loader_test.cpp
> +TEST_F(MeshLoaderTestFixture, loading_valid_ascii_stl_file) {
Isn't this actually loading an "invalid" ascii STL file now?  That is, we are changing this from valid -> invalid, so we should rename this (and probably the filename as well).

2023-10-09 20:30 UTC, clalancette commented on rviz_rendering_tests/test/mesh_loader_test.cpp
>    std::string mesh_path = "package://rviz_rendering_tests/test_meshes/valid_extra.stl";
Same comment here; I think we should probably rename this to `invalid_extra.stl`.

2023-10-16 11:25 UTC, ahcorde commented
We are rejecting files which are not well-formed and this is the current behaviour of ROS 1.

2023-10-16 11:30 UTC, clalancette approved these changes
Thanks for the changes!  This looks good to me with green CI.

2023-10-16 11:39 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19660)](http://ci.ros2.org/job/ci_linux/19660/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14167)](http://ci.ros2.org/job/ci_linux-aarch64/14167/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20383)](http://ci.ros2.org/job/ci_windows/20383/)

2023-10-16 15:57 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19665)](http://ci.ros2.org/job/ci_linux/19665/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14172)](http://ci.ros2.org/job/ci_linux-aarch64/14172/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20388)](http://ci.ros2.org/job/ci_windows/20388/)

2023-10-16 20:31 UTC, merged