Include MeshShape class
ros2/rviz pull request #1064
Opened 2023-09-14 11:54 UTC by ahcorde

Related with this issue: https://github.com/ros2/rviz/issues/763

2023-10-17 22:01 UTC, clalancette requested changes
I've left two relatively minor comments.  Once those are fixed, I'm happy with this.

2023-10-17 22:01 UTC, clalancette commented on rviz_rendering/include/rviz_rendering/mesh_shape.hpp
This is a minor point, but I kind of feel like this file should be in the `objects` subdirectory.  That is, it seems to be an object in its own right, and basically everything else that derives from `Shape` is in the object subdirectory.

@ahcorde What do you think?

2023-10-17 22:01 UTC, clalancette commented on rviz_rendering/include/rviz_rendering/mesh_shape.hpp
> +}
Instead of doing this, can we just `#include` the appropriate Ogre header?  We should also probably add includes for SceneNode, Vector3, SceneManager, etc in here as well.

2023-10-30 13:27 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19695)](http://ci.ros2.org/job/ci_linux/19695/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14201)](http://ci.ros2.org/job/ci_linux-aarch64/14201/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20425)](http://ci.ros2.org/job/ci_windows/20425/)

2023-10-30 22:03 UTC, clalancette approved these changes
This looks good to me with green CI.

2023-10-31 09:05 UTC, ahcorde commented
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20430)](http://ci.ros2.org/job/ci_windows/20430/)

2023-10-31 16:48 UTC, merged