RVIZ_RENDERING_PUBLIC to export class RenderSystem
ros2/rviz pull request #1072
Opened 2023-10-07 01:34 UTC by felixf4xu

class RenderSystem is exported

this will fix #1069

2023-10-07 12:51 UTC, clalancette requested changes

2023-10-07 12:51 UTC, clalancette commented on rviz_rendering/include/rviz_rendering/render_system.hpp
> +  /// return GLSL Version as integer, e.g. 150 for GLSL 1.50
There is whitespace at the end of this line, which is why CI is unhappy.  Once that is fixed, I'll give full CI a shot on this.

2023-10-07 14:09 UTC, felixf4xu commented
@clalancette new commit added to remove the white space.

2023-10-07 18:03 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19622)](http://ci.ros2.org/job/ci_linux/19622/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14130)](http://ci.ros2.org/job/ci_linux-aarch64/14130/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20344)](http://ci.ros2.org/job/ci_windows/20344/)

2023-10-09 08:09 UTC, ahcorde commented
warning is unrelated. Merging

2023-10-09 08:09 UTC, merged