Handle missing effort limit in URDF
ros2/rviz pull request #1084
Opened 2023-11-06 16:54 UTC by roncapat

Fixes #1083

2023-11-06 19:15 UTC, clalancette requested changes
A couple of small things to fix, then I'm happy with this.

2023-11-06 19:15 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +          "Joint `%s` has no <limit> tag in URDF. Effort plugin needs to know the effort "
```suggestion
          "Joint '%s' has no <limit> tag in URDF. Effort plugin needs to know the effort "
```

(it is just more similar to what we do elsewhere)

2023-11-06 19:15 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +        RCLCPP_WARN(
I'll suggest you add `#include <rclcpp/logging.hpp>` to the top of this file.

2023-11-07 21:23 UTC, clalancette approved these changes
Looks good to me!  I'll run CI on it next.

2023-11-07 21:24 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19742)](http://ci.ros2.org/job/ci_linux/19742/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14246)](http://ci.ros2.org/job/ci_linux-aarch64/14246/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20468)](http://ci.ros2.org/job/ci_windows/20468/)

2023-11-08 13:30 UTC, merged

2023-11-09 08:59 UTC, ahcorde commented
https://github.com/Mergifyio backport humble iron