Add fullscreen startup option
ros2/rviz pull request #1097
Opened 2023-11-20 23:22 UTC by paulerikf

This PR adds the "--fullscreen" command-line option, which allows rviz to start up in fullscreen mode. This flag is already in rviz1 - originally added by @rhaschke ([Original PR](https://github.com/ros-visualization/rviz/pull/1413)).

2023-11-21 09:30 UTC, ahcorde requested changes
LGTM, just a minor comment

2023-11-21 09:30 UTC, ahcorde commented on rviz_common/src/rviz_common/visualizer_app.cpp
> +  parser.addOption(fullscreen_option);
```suggestion
  QCommandLineOption fullscreen_option(
    "fullscreen",
    "Start RViz in fullscreen mode.");
  parser.addOption(fullscreen_option);
```

2023-11-27 20:54 UTC, paulerikf commented
Great, thanks for taking a look. Should be o.k. now.

2023-11-28 09:59 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19892)](http://ci.ros2.org/job/ci_linux/19892/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14376)](http://ci.ros2.org/job/ci_linux-aarch64/14376/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20599)](http://ci.ros2.org/job/ci_windows/20599/)

2023-11-29 15:51 UTC, paulerikf commented
@ahcorde Anything remaining for me to do to get this merged?

2023-11-29 15:53 UTC, merged

2023-11-29 15:53 UTC, ahcorde commented
Not really, merged! thank you for your contribution @paulerikf