Implement reset time service
ros2/rviz pull request #1109
Opened 2023-12-21 07:50 UTC by hyunseok-yang

I had hope the service for resetting time to utlize in the simulation environment and I've implemented.
There is resetting simulation scenario in my work.

This implementation provides ros2 service to reset the time in rviz2.

So now rviz2 can reset the time by short cut key(Ctrl+R #1088) or service call.

The service name is `/rviz/reset_time`.

```
$ ros2 service list
/rviz/describe_parameters
/rviz/get_parameter_types
/rviz/get_parameters
/rviz/get_type_description
/rviz/list_parameters
/rviz/reset_time
/rviz/set_parameters
/rviz/set_parameters_atomically
```

The time in rviz2 can be reset through below command.

`ros2 service call /rviz/reset_time std_srvs/srv/Empty {}`

I implemented the member function that it can reset time which is already added in #1088.
Just functionalize the code.

2023-12-21 07:56 UTC, hyunseok-yang commented
@ahcorde 
Hi, Cordero
Could you review my PR.  
I think it is kind of extention work for #1088(Reset time by Ctrl+R).

I hope you can take a look if you have spare time :)

2023-12-21 10:54 UTC, ahcorde requested changes
Do you mind to fix [uncrustify](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/uncrustify/) and [cpplint](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/cpplint/) ?

2023-12-21 11:42 UTC, hyunseok-yang commented
> Do you mind to fix [uncrustify](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/uncrustify/) and [cpplint](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/cpplint/) ?


oops, I will check the cpplint and uncrustify.

let you know when it finished 

thank you!

have a good day

2023-12-26 01:07 UTC, hyunseok-yang commented
> > Do you mind to fix [uncrustify](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/uncrustify/) and [cpplint](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/cpplint/) ?
> 
> oops, I will check the cpplint and uncrustify.
> 
> let you know when it finished
> 
> thank you!
> 
> have a good day
> 
> according to this link [uncrustify](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/uncrustify/) , it says passed.
> 
> do I need to recheck uncrustify also?

Hm, it's little strange... Both of result saying "Passed" in Jenkings

![image](https://github.com/ros2/rviz/assets/21001946/bea25db1-0def-42dc-98ec-8f3c3da3e363)

![image](https://github.com/ros2/rviz/assets/21001946/23bd7591-2fd1-43aa-bd66-bdb53daab95f)


Anyway, I confirmed that there was 1 error with cpplint on my local build environment..
I modified it and pushed again. 
Let's see what Jenkin will say :)

2023-12-26 02:23 UTC, hyunseok-yang commented
> > > Do you mind to fix [uncrustify](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/uncrustify/) and [cpplint](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/cpplint/) ?
> > 
> > 
> > oops, I will check the cpplint and uncrustify.
> > let you know when it finished
> > thank you!
> > have a good day
> > according to this link [uncrustify](https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/353/testReport/junit/(root)/projectroot/uncrustify/) , it says passed.
> > do I need to recheck uncrustify also?
> 
> Hm, it's little strange... Both of result saying "Passed" in Jenkings
> 
> ![image](https://private-user-images.githubusercontent.com/21001946/292785856-bea25db1-0def-42dc-98ec-8f3c3da3e363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTYxNjMsIm5iZiI6MTcwMzU1NTg2MywicGF0aCI6Ii8yMTAwMTk0Ni8yOTI3ODU4NTYtYmVhMjVkYjEtMGRlZi00MmRjLTk4ZWMtOGYzYzNkYTNlMzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAxNTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NDc3Yjg5Mzc3MzU3ZGNiZjFiNGE2NzE4ODVjMTY3MDFmZjYzZTBiZjlhNjYyZDQ0ZGZhZWUyZTM5MDYzMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sVnBcszC8rgbtQj2upIITfe_tjo8niJflqtzBr9bRx0)
> 
> ![image](https://private-user-images.githubusercontent.com/21001946/292785871-23bd7591-2fd1-43aa-bd66-bdb53daab95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTYxNjMsIm5iZiI6MTcwMzU1NTg2MywicGF0aCI6Ii8yMTAwMTk0Ni8yOTI3ODU4NzEtMjNiZDc1OTEtMmZkMS00M2FhLWJkNjYtYmRiNTNkYWFiOTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAxNTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MDkyMDE4MDkxZTlkZmExZDExMWJhODJkYWExMTExMWUzY2M0MTFjODQ0YmQ4ODBkYmQ4N2I0MTY2ZDg0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHFIMqbjGIvznCvKtWaFplhhTfxB2oO4EzN_gocmRCU)
> 
> Anyway, I confirmed that there was 1 error with cpplint on my local build environment.. I modified it and pushed again. Let's see what Jenkin will say :)

Now I checked the failed case and will edit the code soon! 
![image](https://github.com/ros2/rviz/assets/21001946/7af0d0c8-881b-4387-b6a5-c93dcd713272)

2023-12-26 04:43 UTC, hyunseok-yang commented
@ahcorde Hello, Cordero
I think latest changes are passed now :)

Could you review it?

2023-12-26 09:04 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20006)](http://ci.ros2.org/job/ci_linux/20006/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14470)](http://ci.ros2.org/job/ci_linux-aarch64/14470/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20716)](http://ci.ros2.org/job/ci_windows/20716/)

2023-12-26 16:17 UTC, merged

2023-12-27 02:21 UTC, hyunseok-yang commented
@ahcorde Thank you