Append measured subscription frequency to topic status
ros2/rviz pull request #1113
Opened 2023-12-27 02:28 UTC by Yadunund

Addresses https://github.com/ros2/rviz/issues/1112

<img width="1464" alt="image" src="https://github.com/ros2/rviz/assets/13482049/f7c02ee3-bdfc-41d5-81f9-672a71101f4f">

2023-12-27 06:27 UTC, yang19900808 commented
@Yadunund 
Good job buddy, I also implement this method as shown in the following picture.
![lQLPJw3NPBARtxPNAV3NAhSwCtq8inB2w2QFfBiznHMaAA_532_349](https://github.com/ros2/rviz/assets/45547893/1c7629a1-4981-45d7-937f-ae76a20bcab4)

Will this feature be integrated into future version?

2023-12-27 07:33 UTC, ahcorde requested changes
uncrustify is failing https://build.ros2.org/job/Rpr__rviz__ubuntu_jammy_amd64/356/testReport/junit/(root)/projectroot/uncrustify/

2023-12-27 11:12 UTC, Yadunund commented
@ahcorde fixed!

2023-12-27 12:00 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20011)](http://ci.ros2.org/job/ci_linux/20011/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14475)](http://ci.ros2.org/job/ci_linux-aarch64/14475/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20721)](http://ci.ros2.org/job/ci_windows/20721/)

2023-12-28 10:12 UTC, merged

2024-01-25 12:35 UTC, ahcorde commented
https://github.com/Mergifyio backport humble iron

2024-05-23 14:29 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-jazzy-jalisco-released/37862/1