Set Contentsmargin for RenderPanel to 0 to avoid borders in fullscreen mode
ros2/rviz pull request #1228
Opened 2024-07-09 14:29 UTC by bochen87

Set Contentsmargin for RenderPanel to 0 to avoid borders in fullscreen mode. Fixes #1024

2024-07-19 08:41 UTC, ahcorde approved these changes

2024-07-19 08:43 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21518)](http://ci.ros2.org/job/ci_linux/21518/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15800)](http://ci.ros2.org/job/ci_linux-aarch64/15800/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1014)](http://ci.ros2.org/job/ci_linux-rhel/1014/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22234)](http://ci.ros2.org/job/ci_windows/22234/)

2024-07-19 12:21 UTC, ahcorde requested changes
Do you mind to merge with `rolling` ? then CI warnings should disappeared

2024-07-20 11:08 UTC, bochen87 commented
> Do you mind to merge with `rolling` ? then CI warnings should disappeared

sure, how do i do that?

2024-07-22 08:13 UTC, ahcorde commented
You can type something like this

```bash
git fetch
git merge origin/rolling
git push origin rolling
```

2024-07-22 08:23 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21520)](http://ci.ros2.org/job/ci_linux/21520/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15802)](http://ci.ros2.org/job/ci_linux-aarch64/15802/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1018)](http://ci.ros2.org/job/ci_linux-rhel/1018/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22236)](http://ci.ros2.org/job/ci_windows/22236/)

2024-07-22 11:37 UTC, merged

2024-07-24 08:02 UTC, bochen87 commented
@ahcorde Can we also backport this to jazzy?

2024-07-24 08:12 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy

2024-08-12 15:06 UTC, bochen87 commented
> https://github.com/Mergifyio backport jazzy

Thanks for backporting! Is it possible to tag a new version so it get's released in the next cycle?

2024-08-19 09:19 UTC, ahcorde commented
> > https://github.com/Mergifyio backport jazzy
> 
> Thanks for backporting! Is it possible to tag a new version so it get's released in the next cycle?

https://github.com/ros/rosdistro/pull/42481