Added common test for rviz_common
ros2/rviz pull request #1232
Opened 2024-07-11 11:20 UTC by ahcorde

2024-07-22 11:28 UTC, ahcorde commented
friendly ping @clalancette

2024-07-24 18:18 UTC, clalancette requested changes
I've left a whole slew of really minor things to fix.  Once that is done and CI is green, this is good to go.

2024-07-24 18:18 UTC, clalancette commented on rviz_common/include/rviz_common/properties/regex_filter_property.hpp
> +// Redistribution and use in source and binary forms, with or without
```suggestion

// Redistribution and use in source and binary forms, with or without
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/include/rviz_common/transformation/frame_transformer.hpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/properties/file_picker.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/properties/file_picker.hpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/properties/file_picker_property.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/properties/grouped_checkbox_property.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/properties/grouped_checkbox_property_group.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/properties/regex_filter_property.cpp
> +// Redistribution and use in source and binary forms, with or without
```suggestion

// Redistribution and use in source and binary forms, with or without
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/transformation/identity_frame_transformer.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/transformation/identity_frame_transformer.hpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/transformation/transformation_manager.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/transformation_panel.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/src/rviz_common/transformation_panel.hpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/display_context_fixture.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/display_context_fixture.hpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/frame_manager_test.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/interaction/mock_selection_renderer.hpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/interaction/selection_handler_test.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/interaction/selection_manager_test.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/interaction/selection_test_fixture.hpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/mock_frame_transformer.hpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/transformation/identity_frame_transformer_test.cpp
> +//
```suggestion
```

2024-07-24 18:18 UTC, clalancette commented on rviz_common/test/transformation/transformation_test_helpers.hpp
> +//
```suggestion
```

2024-07-24 20:29 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21544)](http://ci.ros2.org/job/ci_linux/21544/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15828)](http://ci.ros2.org/job/ci_linux-aarch64/15828/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1039)](http://ci.ros2.org/job/ci_linux-rhel/1039/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22261)](http://ci.ros2.org/job/ci_windows/22261/)

2024-07-24 20:42 UTC, clalancette approved these changes
Looks good to me with green CI!

2024-07-25 07:10 UTC, merged