Fix/processkeyevent
ros2/rviz pull request #1257
Opened 2024-08-07 13:55 UTC by roncapat

Partially fixes #1256.

This is a (probably backportable) patch that allows a Tool to declare its own use "Finished" and make Rviz re-select the default tool.

Please notice that some Tools defined in this codebase return another flag (`Render`, see attached issue) but this is not being handled too. 

### Note:

To process `Render` flag, an API breaking change shall be introduced (maybe in another PR) so that:
```
void ToolManager::handleChar(QKeyEvent * event, RenderPanel * panel)
```
becomes:
```
int ToolManager::handleChar(QKeyEvent * event, RenderPanel * panel)
```
to propagate flags up in the call hierarchy (up to the `VisualizationManager`).

2024-08-07 14:01 UTC, roncapat commented
This should at least backportable up to Iron (tested locally).

2024-08-07 14:14 UTC, clalancette commented
I'm not super familiar with what is going on here.  Can you give a practical example of what doesn't work/works before and after this patch?

2024-08-07 14:26 UTC, roncapat commented
Yep, sure.

Suppose you design a new Tool plugin. Take for example the "2D Pose Estimate" tool on the upper toolbar of RViz. Each Tool can handle mouse events and optionally keyobard events.
Both handlers are designed to return an integer that can currently be set like a bitmask, with one or more of these flags (currently only two available):

https://github.com/ros2/rviz/blob/a72ef90031c25fceb0b9e58ce3fef58fc246584f/rviz_common/include/rviz_common/tool.hpp#L107-L111

Now, only when returned by the mouse event handler these flags are interpreted and used by Rviz to do something. Some of Rviz tools return "Render" flag from keyobard handler, but that return value gets missed. No default tool ever returns "Finished", so nobody noticed that the return value is discarded.

Back to the example. Take "2D Pose Estimate" tool. Now imagine you add a keyboard handle to catch the button "0" (number 0) while the tool is active,  to send a postition estimate of all zeros (like if you want to completely reset the state of a filter). In the handler you send the message, and then you want to tell Rviz "Finished" (like when you select a new pose with the mouse), so that Rviz can deactivete the current tool and enable the fault tool (`Interact`). This is what happens with the mouse handler, but I discovered it is impossible with a keyboard handler, although partil infrastructure has always been there and there are traces of intended usage even in default plugins.

2024-08-12 07:38 UTC, roncapat commented
Any additional info required for this to merge? :)

2024-08-19 09:28 UTC, ahcorde requested changes
you are targeting `rolling`, Why are you not breaking the API  with the new signature ?

I think this is the patch for older versions, isn't it?

2024-08-19 11:22 UTC, roncapat commented
> you are targeting `rolling`, Why are you not breaking the API  with the new signature ?
> 
> I think this is the patch for older versions, isn't it?

Sort of, I thought that this PR alone could be applied to rolling so that it could also be conveniently backported, and then I could submit an API-breaking 2nd PR for the "Render" flag handling, for rolling only.

Let me know if you'd like to proceed in a different way :)

2024-08-19 13:22 UTC, ahcorde approved these changes
> Sort of, I thought that this PR alone could be applied to rolling so that it could also be conveniently backported, and then I could submit an API-breaking 2nd PR for the "Render" flag handling, for rolling only.
> 
> Let me know if you'd like to proceed in a different way :)

Make sense, 

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21671)](http://ci.ros2.org/job/ci_linux/21671/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15953)](http://ci.ros2.org/job/ci_linux-aarch64/15953/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1173)](http://ci.ros2.org/job/ci_linux-rhel/1173/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22384)](http://ci.ros2.org/job/ci_windows/22384/)

2024-08-20 10:01 UTC, roncapat commented
> * Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21671)](http://ci.ros2.org/job/ci_linux/21671/)
> * Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1173)](http://ci.ros2.org/job/ci_linux-rhel/1173/)

May I ask if you could re-trigger please?

2024-08-20 12:03 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21676)](http://ci.ros2.org/job/ci_linux/21676/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1177)](http://ci.ros2.org/job/ci_linux-rhel/1177/)

2024-08-21 07:47 UTC, merged

2024-08-21 08:21 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy

2024-08-21 08:24 UTC, roncapat commented
> https://github.com/Mergifyio backport jazzy

Also iron, please:)

2024-08-21 08:29 UTC, ahcorde commented
https://github.com/Mergifyio backport iron humble