Fix cve into assimp
ros2/rviz pull request #1258
Opened 2024-08-15 18:35 UTC by mosfet80

Updated assimp .. is need to fix cve https://ubuntu.com/security/CVE-2024-40724

2024-08-22 18:11 UTC, MichaelOrlov commented
@clalancette A friendly ping to follow up on this issue.

2024-08-23 08:11 UTC, ahcorde requested changes
We should stick with the Ubuntu Noble version https://blueprints.launchpad.net/ubuntu/noble/+source/assimp which is 5.3.1

2024-08-23 08:23 UTC, mosfet80 commented
the vulnerability has already been reported on the ubuntu site. https://bugs.launchpad.net/ubuntu/+source/assimp
..But ..the bug is being analyzed.

Since this is a security issue, we recommend using the secure version. The version also fixes issues when importing large CAD files.

2024-08-23 12:35 UTC, clalancette commented
> We should stick with the Ubuntu Noble version https://blueprints.launchpad.net/ubuntu/noble/+source/assimp which is 5.3.1

In this particular case, because it is a CVE, I think we should consider updating it.

That said, the last time we did an update like this we caused a bunch of regressions, so I want to take a closer look before we change anything here.

2025-09-08 15:20 UTC, mosfet80 commented
Closed after #1574

2025-09-08 15:21 UTC, closed without merging