Enabling manual space width for TextViewFacingMarker
ros2/rviz pull request #1261
Opened 2024-08-20 13:26 UTC by ayrton04

I found [this](https://robotics.stackexchange.com/questions/111230/rviz2-text-markers-spacing-issue) question on robotics.stackexchange.com, and have been having the same issue with the `TextViewFacing` marker. Apologies if there's a prescribed method for handling this that I've missed.

In any case, this PR allows users to manually specify the width of a space in the `TextViewFacing` marker using the `scale.x` field of the `visualization_msgs::msg::Marker` message. In the "with change" screenshot below, I used a width of 0.2. Note that if no width is specified, we retain the current behaviour.

I'd be happy to instead change the logic that controls the space width by default, but this seemed like it would be less intrusive.

![Screenshot from 2024-08-20 14-19-00](https://github.com/user-attachments/assets/b2ad43e3-a036-4f4e-8b31-a2551a531176)

![image](https://github.com/user-attachments/assets/b1dc946c-279b-4241-8cdf-41ee7a93eaa6)

2024-08-20 13:46 UTC, ahcorde approved these changes

2024-08-20 13:48 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21677)](http://ci.ros2.org/job/ci_linux/21677/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15957)](http://ci.ros2.org/job/ci_linux-aarch64/15957/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1178)](http://ci.ros2.org/job/ci_linux-rhel/1178/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22388)](http://ci.ros2.org/job/ci_windows/22388/)

2024-08-20 15:34 UTC, ahcorde requested changes
uncrustify is failing
```
-  if (new_message->scale.x != 0.0)
-  {
+  if (new_message->scale.x != 0.0) {
```

2024-08-20 15:59 UTC, ayrton04 commented
Yeah, saw that. I fixed it a while ago: https://github.com/ros2/rviz/pull/1261/commits/b121dc1c1cbc44664f75e6b53418d1ea0ed55f54

New build is going: https://build.ros2.org/job/Rpr__rviz__ubuntu_noble_amd64/112/

2024-08-20 18:34 UTC, ayrton04 commented
@ahcorde I believe the build passed.

2024-08-21 07:48 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21686)](http://ci.ros2.org/job/ci_linux/21686/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15961)](http://ci.ros2.org/job/ci_linux-aarch64/15961/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1187)](http://ci.ros2.org/job/ci_linux-rhel/1187/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22391)](http://ci.ros2.org/job/ci_windows/22391/)

2024-08-21 08:08 UTC, ahcorde approved these changes

2024-08-21 11:54 UTC, merged

2024-08-21 11:55 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy humble iron