Work in progress using the new resource retriever apis
ros2/rviz pull request #1262
Opened 2024-08-20 15:27 UTC by mjcarroll

2024-12-17 17:17 UTC, wjwwood commented
Pushed an update that does some clean up and renames the message/service package into `rviz_resource_interfaces`, as well as adds an etag field and uses it to invalidate the cache. Working on finishing the cleanup, deduplicating with `robot_link.cpp` and updating the matching example service that works with this.

2025-01-24 18:12 UTC, asherikov commented
In the context of related discussion in https://github.com/ros/robot_state_publisher/issues/144, I think it would make sense to define the service in a package that is not related to rviz, e.g., meshes can be queried by a node that performs collision checking.

2025-01-27 22:50 UTC, mjcarroll commented
While the service is defined in this repository, it doesn't have any dependency on `rviz`, so it shouldn't incur any extra cost to use it in other packages.

2025-02-19 00:55 UTC, wjwwood commented
@asherikov, as @mjcarroll said you should be able to use this new package without any issue even if it's in the rviz repository and the name implies a connection to rviz. I spoke to @mjcarroll about it, and we agreed that we'd like to see it used in rviz as-is in this pull request before recommending it be used outside of this context and/or moving it to one of the standard message repositories (e.g. `visualization_msgs` or something like that) or to it's own repository under a more general name.

2025-02-19 00:56 UTC, wjwwood commented
Ok, I think this is ready for review. It depends on https://github.com/ros/resource_retriever/pull/103 which is under review now.

2025-02-19 09:37 UTC, ahcorde requested changes

2025-02-19 09:37 UTC, ahcorde commented on rviz_default_plugins/src/rviz_default_plugins/ros_resource_retriever.cpp
> +#include <string>
```suggestion
#include <stdexcept>
#include <string>
```

2025-02-19 09:38 UTC, ahcorde commented
Pulls: ros/resource_retriever#103, ros2/rviz#1262
Gist: https://gist.githubusercontent.com/ahcorde/13502377fe7128ba0a2d910a7c9dfd91/raw/2b32e8eeb4f5c28e7b0afbbdb6ea9f15771e6234/ros2.repos
BUILD args:  --packages-above-and-dependencies resource_retriever
TEST args:  --packages-above resource_retriever
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15221
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22564)](http://ci.ros2.org/job/ci_linux/22564/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16809)](http://ci.ros2.org/job/ci_linux-aarch64/16809/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2080)](http://ci.ros2.org/job/ci_linux-rhel/2080/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23357)](http://ci.ros2.org/job/ci_windows/23357/)

2025-02-19 20:50 UTC, ahcorde requested changes

2025-02-19 20:50 UTC, ahcorde commented on rviz_rendering/src/rviz_rendering/mesh_loader.cpp
> +    Ogre::DataStreamPtr stream(new Ogre::MemoryDataStream(*res->data.data(), res->data.size()));
```suggestion
    Ogre::DataStreamPtr stream(new Ogre::MemoryDataStream(
      const_cast<void*>(reinterpret_cast<void const *>(res->data.data())), res->data.size()));
```

2025-02-19 20:58 UTC, ahcorde requested changes

2025-02-19 20:58 UTC, ahcorde commented on rviz_rendering_tests/test/mesh_loader_test.cpp
>    ASSERT_THAT(output, HasSubstr("Error retrieving file"));
```suggestion
  ASSERT_THAT(mesh, nullptr);
```

2025-02-19 21:13 UTC, ahcorde commented on rviz_default_plugins/src/rviz_default_plugins/robot/robot_link.cpp
> +  plugins.push_back(std::make_shared<RosResourceRetriever>(context_->getRosNodeAbstraction()));
other issue is happening here:

```
C++ exception with description "ROS node abstraction interface not valid" thrown in the test body
```

2025-03-05 01:20 UTC, wjwwood commented on rviz_rendering_tests/test/mesh_loader_test.cpp
>    ASSERT_THAT(output, HasSubstr("Error retrieving file"));
I'm confused about this change, why are we not using the `output` variable anymore? If that's correct, then why not remove the line before it too?

2025-03-05 01:21 UTC, wjwwood commented on rviz_default_plugins/src/rviz_default_plugins/robot/robot_link.cpp
> +  plugins.push_back(std::make_shared<RosResourceRetriever>(context_->getRosNodeAbstraction()));
I'll look into this one more.

2025-03-05 13:57 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22636)](http://ci.ros2.org/job/ci_linux/22636/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16879)](http://ci.ros2.org/job/ci_linux-aarch64/16879/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2153)](http://ci.ros2.org/job/ci_linux-rhel/2153/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23447)](http://ci.ros2.org/job/ci_windows/23447/)

2025-04-10 17:10 UTC, wjwwood approved these changes
lgtm

2025-04-10 17:17 UTC, ahcorde commented
Pulls: ros2/rviz#1262
Gist: https://gist.githubusercontent.com/ahcorde/513573fc2eb3cc445958f3586fec043a/raw/adc963b8b924996dfc384fff29798137e83988b3/ros2.repos
BUILD args:  --packages-up-to rviz_common rviz_default_plugins rviz_rendering rviz_rendering_tests rviz_resource_interfaces  --packages-above-and-dependencies rviz_common rviz_default_plugins rviz_rendering rviz_rendering_tests rviz_resource_interfaces
TEST args:  --packages-select rviz_common rviz_default_plugins rviz_rendering rviz_rendering_tests rviz_resource_interfaces  --packages-above rviz_common rviz_default_plugins rviz_rendering rviz_rendering_tests rviz_resource_interfaces
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15657
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=23114)](http://ci.ros2.org/job/ci_linux/23114/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=17331)](http://ci.ros2.org/job/ci_linux-aarch64/17331/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2587)](http://ci.ros2.org/job/ci_linux-rhel/2587/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23989)](http://ci.ros2.org/job/ci_windows/23989/)

2025-04-10 20:30 UTC, merged

2025-04-11 21:41 UTC, wjwwood commented
Thanks for your help @ahcorde!