Compressed Image Display
ros2/rviz pull request #1288
Opened 2024-10-24 15:38 UTC by mjforan

Addresses #738 

I added `RosTopicMultiProperty`, which extends `RosTopicProperty` with a list of message types instead of one single type. This allows the `ImageDisplay` to show raw and compressed image topics together in its selector list. `ImageDisplay` was altered to use an `image_transport` subscriber so it can seamlessly display any installed image type. There are also a handful of frivolous changes to comply with the style linters.

Tested with raw and compressed images. Assuming the other types work as well because the conversion happens in the `image_transport` library.

Uncertainties:
 - `RosTopicMultiProperty`: Is the name ok? Is there a simpler way to achieve my goal without adding a one-off property?
 - `plugin_description.xml`: I added the other `image_transport` topic types here so Image Display appears in the "Add/By topic" menu. Adding the display will fail if the associated `image_transport` plugin is not installed. Should `ros-$ROS_DISTRO-image-transport-plugins` be added to `package.xml`?

2024-11-07 16:04 UTC, mjforan commented
Added a property to manually override image transport type. Rviz determines the transport by checking the topic name against image_transport conventions, e.g. `camera_name/raw`, `camera_name/compressed`, etc. If this is not the case, the transport must be set manually.
I also fixed the crash caused by adding a topic with an unavailable transport. Instead it will provide an error on the status property saying the transport is not installed.

2024-11-08 13:11 UTC, ahcorde requested changes
This is wierd

![rviz2_image_transport](https://github.com/user-attachments/assets/47bd5687-cd15-4418-b1b5-47a2794c20f1)

I had a default `rviz.config` file with an image display and Rviz2 crashes, do you mind to take a look ? we don't want to break user.

2024-11-08 13:11 UTC, ahcorde commented on rviz_common/include/rviz_common/properties/ros_topic_multi_type_property.hpp
> +    const QString & name = QString(), const QString & default_value = QString(),
include `<QString>`

2024-11-08 13:18 UTC, mjforan commented on rviz_common/include/rviz_common/properties/ros_topic_multi_property.hpp
> +    const QString & name = QString(), const QString & default_value = QString(),
None of the other properties do. I don't mind adding it, but they should all be consistent.

2024-11-08 14:03 UTC, clalancette commented on rviz_common/include/rviz_common/properties/ros_topic_multi_property.hpp
> +    const QString & name = QString(), const QString & default_value = QString(),
> None of the other properties do. I don't mind adding it, but they should all be consistent.

Agreed, but we may as well add it here and then do a separate PR to add it to the others.

2024-11-08 14:37 UTC, mjforan commented
@ahcorde 
> This is wierd

Sorry about that, I have pushed a fix.

> I had a default `rviz.config` file with an image display and Rviz2 crashes, do you mind to take a look ? we don't want to break user.

Please provide details so I can reproduce your issue.

2024-11-08 14:49 UTC, mjforan commented
I would like to list the available image transports in a status message. However, `setStatusStd` only seems to work when it is called from `subscribe`, not `onInitialize` or `updateTopic`. Any idea why?

The status message doesn't really matter _except_ the transport->message type map is hard-coded, so we will want a warning if a new transport type is used which does not exist in the map.

2024-11-12 16:18 UTC, mjforan commented
I noticed the Jazzy version of `image_transport` finally allows passing in custom QoS so I updated the API here to match. This is change not compatible with previous versions of ROS.

2024-11-13 13:32 UTC, mjforan commented
Can `ImageDisplay` be combined with the parent class `ImageTransportDisplay`? That would allow `CameraDisplay` to also show compressed image topics.

2025-02-21 17:39 UTC, mjforan commented
@mjcarroll hoping you can take over / reassign Chris' review :)

2025-03-05 14:31 UTC, mjforan commented
@ahcorde

2025-03-13 21:01 UTC, mjforan commented
@cottsay

2025-03-24 16:23 UTC, ahcorde requested changes
I run a image publisher and there is an issue. I'm able to subscribe to `raw` and `compressed` but I'm not able to subscribe to `zstd`.

2025-03-24 16:23 UTC, ahcorde commented on rviz_default_plugins/CMakeLists.txt
> +    find_package(image_transport_plugins REQUIRED)
remove this `find_package` because `image_transport_plugins` is not a core package and this is not used anywhere

2025-03-24 16:23 UTC, ahcorde commented on rviz_common/src/rviz_common/properties/ros_topic_multi_type_property.cpp
> +  std::map<std::string, std::vector<std::string>> published_topics =
include `<vector>`

2025-03-24 16:23 UTC, ahcorde commented on rviz_default_plugins/include/rviz_default_plugins/displays/image/image_display.hpp
> +  uint32_t messages_received_;
include `<cstdint)>`

2025-03-24 16:23 UTC, ahcorde commented on rviz_default_plugins/test/rviz_default_plugins/publishers/compressed_image_publisher.hpp
> +using namespace std::chrono_literals;  // NOLINT
include `<chrono>`

2025-03-24 16:23 UTC, ahcorde commented on rviz_default_plugins/test/rviz_default_plugins/publishers/compressed_image_publisher.hpp
> +        std::bind(&CompressedImagePublisher::timer_callback, this));
include `<utility>`

2025-03-24 16:23 UTC, ahcorde commented on rviz_default_plugins/test/rviz_default_plugins/publishers/compressed_image_publisher.hpp
> +    publisher = this->create_publisher<sensor_msgs::msg::CompressedImage>(topic_name, 10);
move implementation to `cpp`

2025-03-24 18:11 UTC, mjforan commented on rviz_default_plugins/test/rviz_default_plugins/publishers/compressed_image_publisher.hpp
> +        std::bind(&CompressedImagePublisher::timer_callback, this));
For what? Do you mean `<functional>` for `std::bind`?

2025-03-24 19:14 UTC, mjforan commented
> I run a image publisher and there is an issue. I'm able to subscribe to `raw` and `compressed` but I'm not able to subscribe to `zstd`.

All the plugins are handled by `image_transport`. The only transport-specific part of my code is the map saying `zstd` transport uses `sensor_msgs/msg/CompressedImage` messages. Did you use the transport override property to specify `zstd`?

2025-03-27 12:12 UTC, mjforan commented
@ahcorde

2025-03-27 12:19 UTC, ahcorde requested changes
You included many changes which are not related with this PR, I mean the headers inclusion. Do you mind to split the PR in two ?

2025-03-28 12:38 UTC, ahcorde requested changes

2025-03-28 12:38 UTC, ahcorde commented on rviz_default_plugins/package.xml
> +  <test_depend>image_transport_plugins</test_depend>
`image_transport_plugins` is not a [ROS 2 core package](https://github.com/ros2/ros2/blob/rolling/ros2.repos), we should remove this from here

2025-03-28 12:38 UTC, ahcorde commented on rviz_default_plugins/package.xml
> +  <test_depend>vision_opencv</test_depend>
Same idea here, `vision_opencv` is not a core package, we can't use this one here

2025-03-28 12:42 UTC, mjforan commented on rviz_default_plugins/package.xml
> +  <test_depend>vision_opencv</test_depend>
OpenCV is used in compressed_image_publisher.hpp, to encode a jpeg image.

2025-04-02 11:59 UTC, mjforan commented
@ahcorde

2025-05-15 14:36 UTC, mjforan commented
@ahcorde

2025-05-19 12:47 UTC, mjforan commented
@cottsay

2025-05-19 12:49 UTC, mjforan commented
@audrow @sloretz @clalancette @MichaelOrlov

2025-05-19 15:04 UTC, ahcorde approved these changes

2025-05-19 15:05 UTC, ahcorde commented
Pulls: ros2/rviz#1288
Gist: https://gist.githubusercontent.com/ahcorde/ccc19f0eb20f1e839b62f6a82860cb56/raw/8ba713dd713ffadefa3801686787117bf9f33380/ros2.repos
BUILD args:  --packages-above-and-dependencies tviz_common rviz_default_plugins
TEST args:  --packages-above tviz_common rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16036
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=23689)](http://ci.ros2.org/job/ci_linux/23689/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=17798)](http://ci.ros2.org/job/ci_linux-aarch64/17798/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3144)](http://ci.ros2.org/job/ci_linux-rhel/3144/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=24399)](http://ci.ros2.org/job/ci_windows/24399/)

2025-05-19 15:08 UTC, ahcorde commented
Pulls: ros2/rviz#1288
Gist: https://gist.githubusercontent.com/ahcorde/753b92fff53f4ae45626059ba1fca518/raw/8ba713dd713ffadefa3801686787117bf9f33380/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_common rviz_default_plugins
TEST args:  --packages-above rviz_common rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16039
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=23692)](http://ci.ros2.org/job/ci_linux/23692/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=17801)](http://ci.ros2.org/job/ci_linux-aarch64/17801/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3147)](http://ci.ros2.org/job/ci_linux-rhel/3147/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=24402)](http://ci.ros2.org/job/ci_windows/24402/)

2025-05-19 16:41 UTC, mjforan commented
The "unstable" builds are caused by GitHub rate limiting. I think they changed something recently because I have been seeing it frequently in my own CI processes.

2025-05-19 17:13 UTC, ahcorde commented
> The "unstable" builds are caused by GitHub rate limiting. I think they changed something recently because I have been seeing it frequently in my own CI processes.

This is is related with RViz in particular with `rviz_default_plugins.image_display_test`, there is a segfault

2025-05-19 18:22 UTC, mjforan commented
Oh, I see now. That must be the result of some changes outside of this PR because it was not failing in March. I will look into it.

2025-08-15 21:03 UTC, ijnek commented
We would like to get this PR over the line. Is there anything we can do to help here?

2025-08-15 21:10 UTC, mjforan commented
@ijnek sorry, I am in the middle of a cross-country move so I haven't been able to look at this for a while. As of May a new segfault was the only blocker for this PR. I can't provide much support right now but I'll be on it again in a month or so.

2025-08-24 02:27 UTC, mjforan commented
@ahcorde The test build reports errors apparently stemming from point cloud display updates in 7248938. Everything builds successfully on my system so maybe there is a problem with the automated build setup.

2025-08-31 16:47 UTC, mjforan commented
I putting this PR on hold until the issues regarding abstract node interfaces are worked out.

2025-12-12 14:12 UTC, JoLichtenfeld commented
Hi, is this PR still active?
I think the `RosTopicMultiProperty` could also be useful for the [PointCloud2TransportDisplay](https://github.com/ros2/rviz/blob/jazzy/rviz_default_plugins/include/rviz_default_plugins/displays/pointcloud/point_cloud_transport_display.hpp).

This suffers from the same problem that topics of type `point_cloud_interfaces/msg/CompressedPointCloud2` are not shown in the display's dropdown topic selection.

Would it make sense to move this (`RosTopicMultiProperty` ) to a separate PR? Then I could continue working on the PointCloud2TransportDisplay.

2025-12-12 14:19 UTC, mjforan commented
@JoLichtenfeld 
Yes. After Dec 25 I will get this going again.
If that is not soon enough, you're welcome to split out what you need into a separate PR.

2025-12-12 14:53 UTC, JoLichtenfeld commented
> @JoLichtenfeld Yes. After Dec 25 I will get this going again. If that is not soon enough, you're welcome to split out what you need into a separate PR.

Perfect, then I will wait for it.

2026-01-04 21:07 UTC, mjforan commented
I'm encountering memory issues in the compressed image transport plugin (deb package) but can't reproduce with a source build. They are both on the most recent version (6.2.2).
Maybe it is something particular with my setup. @ahcorde could you please run the test suite?

2026-03-17 14:21 UTC, ahcorde commented
Pulls: ros2/rviz#1288
Gist: https://gist.githubusercontent.com/ahcorde/e1a0d05cc384c1f8d67e6c0cc8ea4bf5/raw/98fc29ef693e8b884e8f658a15b4a9ec07062894/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_common rviz_default_plugins
TEST args:  --packages-above rviz_common rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18518
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=28084)](http://ci.ros2.org/job/ci_linux/28084/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=21054)](http://ci.ros2.org/job/ci_linux-aarch64/21054/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=7934)](http://ci.ros2.org/job/ci_linux-rhel/7934/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=27026)](http://ci.ros2.org/job/ci_windows/27026/)

2026-03-18 09:53 UTC, ahcorde commented
Pulls: ros2/rviz#1288
Gist: https://gist.githubusercontent.com/ahcorde/fdec2fc9dd95e43181ca4ac3ac3903b7/raw/98fc29ef693e8b884e8f658a15b4a9ec07062894/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_common rviz_default_plugins
TEST args:  --packages-above rviz_common rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18541
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=28112)](http://ci.ros2.org/job/ci_linux/28112/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=21083)](http://ci.ros2.org/job/ci_linux-aarch64/21083/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=7963)](http://ci.ros2.org/job/ci_linux-rhel/7963/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=27049)](http://ci.ros2.org/job/ci_windows/27049/)

2026-03-18 10:44 UTC, ahcorde requested changes

2026-03-18 10:44 UTC, ahcorde commented on rviz_default_plugins/include/rviz_default_plugins/displays/image/image_display.hpp
> +  };
uhmm, I don't like this part, if we add a new plugin I nned to modify these lines. 

Do you mind to check this PR https://github.com/ros-perception/image_common/pull/394

2026-03-18 11:21 UTC, peci1 commented on rviz_default_plugins/include/rviz_default_plugins/displays/image/image_display.hpp
> +  };
As commented in https://github.com/ros-perception/image_common/pull/394 , it's not that easy to get a type of a transport (because it can be a multi-topic/multi-type transport).

It would seem more suitable to me to expose a function like `isTransportTopic()` to the transport plugins. However, for it to be usable, it would need to be a static function, and as such, it might be difficult to iterate over it in a generic way. Another option would be to make it an instance method of the plugins and force ImageTransport to create an instance of each plugin which could then be queried. However, that would be a significant change that would basically mean that all dynamic libraries connected with all transports would be loaded into all ImageTransport instances. Maybe it's okay, but it could be a significant change.

2026-03-18 11:37 UTC, peci1 commented on rviz_default_plugins/include/rviz_default_plugins/displays/image/image_display.hpp
> +  };
Anyway, the added `getMessageType()` function would not help here. You'd need instances of the transports to call it, but you only have their names.

Maybe RViz could create an instance for each loadable transport and use that instance for these kinds of queries?

2026-03-18 12:09 UTC, peci1 commented on rviz_default_plugins/plugins_description.xml
>    </class>
Do you know where is this list used? Is it used to select which topics should be shown when adding a new display by topic name?

2026-03-18 15:18 UTC, mjforan commented on rviz_default_plugins/plugins_description.xml
>    </class>
Correct

2026-03-18 17:49 UTC, peci1 commented on rviz_default_plugins/plugins_description.xml
>    </class>
And is there a way to help RViz finding all the installed transport packages and their supported types, or would this be a limitation that's hard to overcome?

2026-03-19 03:47 UTC, mjforan commented on rviz_default_plugins/plugins_description.xml
>    </class>
Gave it a try in [37f32d2](https://github.com/ros2/rviz/pull/1288/commits/37f32d2056c03cca88198eaa4ed91b71daa6a9d6). Added a method `DisplayFactory::updatePluginMessageTypes` which sets a cache value to use in `DisplayFactory::getMessageTypes` instead of parsing the XML. Didn't have time to test but it seems straightforward.

2026-03-31 13:15 UTC, mjforan commented
@ahcorde I intentionally removed the compressed image type from plugin_description.xml. Once the other PR settles I will update this code to populate message types based on the installed image transport plugins.

2026-03-31 13:40 UTC, ahcorde commented
> @ahcorde I intentionally removed the compressed image type from plugin_description.xml. Once the other PR settles I will update this code to populate message types based on the installed image transport plugins.

Nice! Thank you!

2026-04-06 02:29 UTC, mjforan commented
~~Requires https://github.com/ros-perception/image_transport_plugins/pull/217~~

2026-04-06 03:15 UTC, mjforan commented on rviz_default_plugins/plugins_description.xml
>    </class>
This is not yet working. I can see it being set properly in the cache but then it is not found later when the dialog looks up the message types. I'm guessing they have different instances of DisplayFactory.

2026-04-07 03:08 UTC, mjforan commented on rviz_default_plugins/plugins_description.xml
>    </class>
Fixed! It was getting overwritten by `fillCacheForAllClassElements`.

2026-04-07 09:47 UTC, ahcorde requested changes
Overall LGTM. I just have a comment related to functionality

First time that I try to add the display I can't  see the image transport types

<img width="499" height="695" alt="Image" src="https://github.com/user-attachments/assets/2183d1cd-de11-4841-878b-b1bea7c92040" />

When I add one Image Display then I can see the image transport types:

<img width="500" height="695" alt="Image" src="https://github.com/user-attachments/assets/7549567d-f9f3-4ef5-bf16-45ec6b27f534" />

2026-04-07 11:41 UTC, peci1 requested changes
I have a few comments inline. After they're resolved, this PR is good to go!

2026-04-07 11:41 UTC, peci1 commented on rviz_common/src/rviz_common/properties/ros_topic_multi_type_property.cpp
> +    rviz_ros_node_.lock()->get_topic_names_and_types();
Couldn't the result of lock() be nullptr?

2026-04-07 11:41 UTC, peci1 commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/get_transport_from_topic.cpp
> +          sub_loader.getPluginManifestPath(plugin_class), plugin_class);
Misleading indentation

2026-04-07 11:41 UTC, peci1 commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/get_transport_from_topic.cpp
> +          if (!message_type.empty()) {
Use `image_transport::get_transport_name_from_manifest()` . It has the fallback to extraction from lookup name.

2026-04-07 11:41 UTC, peci1 commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/image_display.cpp
> +    [this](Ogre::SceneNode * scene_node) {scene_node->attachObject(screen_rect_.get());});
This is a nitpick, but I find the new formatting much less readable than the previous one.

2026-04-07 11:41 UTC, peci1 commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/image_display.cpp
> +    const std::string class_without_suffix =
use `image_transport::get_transport_name_from_manifest()`

2026-04-07 11:41 UTC, peci1 commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/image_display.cpp
> +  ->setMessageTypes(message_types);
misleading indentation

2026-04-07 11:41 UTC, peci1 commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/image_display.cpp
> +  ((rviz_common::properties::RosTopicMultiTypeProperty *)topic_property_)
dynamic_cast would be better here?

2026-04-07 11:41 UTC, peci1 commented on rviz_common/include/rviz_common/properties/ros_topic_multi_type_property.hpp
> +    const QSet<QString> & message_types = QSet<QString>(),
Maybe renaming this to `initial_message_types` would be more descriptive?

2026-04-07 11:41 UTC, peci1 commented on rviz_common/include/rviz_common/properties/ros_topic_multi_type_property.hpp
> +  void setMessageTypes(const QSet<QString> & message_types)
Would it make sense to make these get/set methods virtual?

2026-04-12 22:16 UTC, mjforan commented
> First time that I try to add the display I can't see the image transport types

We determine the available image_transport plugins when the ImageDisplay is loaded, so DisplayFactory doesn't know about them at this point.

Option 1: Instantiate the class. Bad for performance and could cause side effects from plugin constructors.

Option 2: Add a static method `ImageDisplay::getMessageTypes` and look it up on the shared library. We would also need an `extern "C"` wrapper to prevent name mangling. Seems ugly for a small piece of functionality used by only one display.

Option 3: Some PluginLib / XML wizardry I'm not familiar with. Maybe add a sub-class which determines runtime message types.

Any ideas?

2026-04-12 22:22 UTC, mjforan commented on rviz_common/src/rviz_common/properties/ros_topic_multi_type_property.cpp
> +    rviz_ros_node_.lock()->get_topic_names_and_types();
This pattern is used in the existing `ros_topic_property`. I assume there is some runtime guarantee that the node has been created before displays are populated.

2026-04-12 22:36 UTC, mjforan commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/image_display.cpp
> +  ->setMessageTypes(message_types);
uncrustify doesn't like indentation here

2026-04-12 22:40 UTC, mjforan commented on rviz_common/include/rviz_common/properties/ros_topic_multi_type_property.hpp
> +  void setMessageTypes(const QSet<QString> & message_types)
What do you mean? Which class would implement them?

2026-04-12 22:49 UTC, mjforan commented on rviz_common/include/rviz_common/properties/ros_topic_multi_type_property.hpp
> +    const QSet<QString> & message_types = QSet<QString>(),
It's understood that constructor fields are "initial" and can be changed later. Should `RosTopicProperty` arguments be renamed to "initial_name", "initial_description", "initial_parent", etc? Seems unnecessarily verbose.

2026-04-12 23:58 UTC, peci1 commented
Thanks for the updates. I didn't have time to check them as I'm leaving for vacation in a few hours. So please don't wait for me with this PR.

2026-04-16 07:53 UTC, ahcorde requested changes

2026-04-16 07:53 UTC, ahcorde commented on rviz_default_plugins/package.xml
> +  <test_depend>image_transport_plugins</test_depend>
we can't include this dependency, this is not a core package

2026-04-16 11:39 UTC, mjforan commented on rviz_default_plugins/package.xml
> +  <test_depend>image_transport_plugins</test_depend>
Removed in [f2d9f50](https://github.com/ros2/rviz/pull/1288/commits/f2d9f50e4e158c4712192bbea6b17728f4680f52)

2026-04-16 13:43 UTC, ahcorde commented
Pulls: ros2/rviz#1288
Gist: https://gist.githubusercontent.com/ahcorde/2922048bc99b1cd6dc0e9d8ea0fb9abb/raw/5524efa70c83582fca1969b04af9e4cbe8a8505d/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_common rviz_default_plugins
TEST args:  --packages-above rviz_common rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18979
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=28740)](http://ci.ros2.org/job/ci_linux/28740/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=21559)](http://ci.ros2.org/job/ci_linux-aarch64/21559/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=8579)](http://ci.ros2.org/job/ci_linux-rhel/8579/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=27608)](http://ci.ros2.org/job/ci_windows/27608/)

2026-04-16 21:18 UTC, ahcorde commented
Pulls: ros2/rviz#1288
Gist: https://gist.githubusercontent.com/ahcorde/c4628dff9c0c34ec74cdb5dc08b45b66/raw/5524efa70c83582fca1969b04af9e4cbe8a8505d/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_common rviz_default_plugins
TEST args:  --packages-above rviz_common rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18981
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=28743)](http://ci.ros2.org/job/ci_linux/28743/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=21561)](http://ci.ros2.org/job/ci_linux-aarch64/21561/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=8581)](http://ci.ros2.org/job/ci_linux-rhel/8581/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=27610)](http://ci.ros2.org/job/ci_windows/27610/)

2026-04-17 08:19 UTC, ahcorde commented
Pulls: ros2/rviz#1288
Gist: https://gist.githubusercontent.com/ahcorde/cccdd9bc1aaa5c460f84edf338b5f6a9/raw/5524efa70c83582fca1969b04af9e4cbe8a8505d/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_common rviz_default_plugins
TEST args:  --packages-above rviz_common rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18985
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=28748)](http://ci.ros2.org/job/ci_linux/28748/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=21566)](http://ci.ros2.org/job/ci_linux-aarch64/21566/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=8591)](http://ci.ros2.org/job/ci_linux-rhel/8591/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=27615)](http://ci.ros2.org/job/ci_windows/27615/)

2026-04-20 10:55 UTC, merged

2026-07-15 13:11 UTC, roncapat commented
Hi, do you confirm there is no backport for this in jazzy?

2026-07-15 13:29 UTC, ahcorde commented
This is breaking API/ABI, I didn't backport it. It's available in Lyrical and Rolling