Nv12 color format
ros2/rviz pull request #1318
Opened 2024-12-26 09:51 UTC by quic-zhaoyuan

### Overview
This PR adds NV12-to-RGB conversion functionality to rviz2. It leverages the newly introduced NV12 encoding in the ROS2 common_interfaces (see https://github.com/ros2/common_interfaces/pull/253). 

### Details
- Introduced a dedicated function `convertNV12ToRGBData()` for NV12 images.
- Ensured correct UV plane indexing according to the updated NV12 memory layout.
- Expanded `setFormatAndNormalizeDataIfNecessary()` to handle the "nv12" encoding.
- Verified that the output size is consistent with the expected 3×width×height RGB buffer.

### Rationale
Previously, rviz2 did not include a built-in NV12 conversion, resulting in garbled or miscolored images when receiving NV12-encoded topics. With the new encoding support merged into common_interfaces, this PR provides a seamless way to correctly display NV12 image streams in rviz2.

### Testing
- Tested locally with NV12 image streams from a camera driver.
- Verified that the displayed image colors match the expected RGB output.

### Dependencies
This PR relies on the changes merged in https://github.com/ros2/common_interfaces/pull/253, which introduced the NV12 encoding definition into sensor_msgs.

---

Thank you for reviewing and considering this PR! If you have any questions or need additional information, please let me know.

2024-12-26 18:11 UTC, ahcorde approved these changes

2024-12-26 18:12 UTC, ahcorde commented
Pulls: ros2/rviz#1318
Gist: https://gist.githubusercontent.com/ahcorde/786fda3ef5979b1e138c79651e557ab1/raw/dfe7832043d13963dcfb61fae91273454b9dc9b7/ros2.repos
BUILD args:  --packages-up-to rviz_default_plugins --packages-above-and-dependencies rviz_default_plugins
TEST args:  --packages-select rviz_default_plugins --packages-above rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15002
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22317)](http://ci.ros2.org/job/ci_linux/22317/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16580)](http://ci.ros2.org/job/ci_linux-aarch64/16580/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1848)](http://ci.ros2.org/job/ci_linux-rhel/1848/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23108)](http://ci.ros2.org/job/ci_windows/23108/)

2024-12-27 01:41 UTC, quic-zhaoyuan commented
Hi @ahcorde ,
According to the log, seems the latest change has not been involved into CI
18:24:03 /tmp/ws/src/rviz/rviz_default_plugins/src/rviz_default_plugins/displays/image/ros_image_texture.cpp:494:56: error: ‘NV12’ is not a member of ‘sensor_msgs::image_encodings’; did you mean ‘NV21’?


Thanks,
Zhaoyuan

2025-01-09 18:25 UTC, christophebedard commented
@ros-pull-request-builder retest this please

2025-01-09 18:28 UTC, christophebedard commented
Oh right, the Rpr CI job listed here on GitHub is expected to fail until a new release of `sensor_msgs` that includes https://github.com/ros2/common_interfaces/pull/253 is made.

2025-01-10 03:20 UTC, zycczy commented
Sure

> Oh right, the Rpr CI job listed here on GitHub is expected to fail until a new release of `sensor_msgs` that includes [ros2/common_interfaces#253](https://github.com/ros2/common_interfaces/pull/253) is made and a sync is done.

2025-01-10 10:42 UTC, ahcorde requested changes
@quic-zhaoyuan Do you mind to merge with rolling ? I think the warnings that I see on the CI are already fixed

2025-01-13 02:07 UTC, quic-zhaoyuan commented
sure, this PR is set to commit into rolling I think

> @quic-zhaoyuan Do you mind to merge with rolling ? I think the warnings that I see on the CI are already fixed

2025-02-17 03:36 UTC, zycczy commented
@ahcorde  can we merge this change to rolling now?

2025-02-17 09:32 UTC, ahcorde requested changes
Sure, do you mind to merge with master?

```bash
git clone https://github.com/quic-qrb-ros/rviz -b nv12_color_format
cd rviz
git remote add ros https://github.com/ros2/rviz
git fetch ros
git merge ros rolling
git push origin nv12_color_format
```

Then I will relaunch CI

2025-02-18 06:31 UTC, quic-zhaoyuan commented
Hi @ahcorde,
Has been updated, I'm not sure why it show "Merging is blocked", there is not a merge commit in the commits list

2025-02-18 11:24 UTC, ahcorde commented
Pulls: ros2/rviz#1318
Gist: https://gist.githubusercontent.com/ahcorde/32f58967ce506f59f3df26c8857c7dbd/raw/46ab81dfe206df5fd25ea0f1a9b1eb2252a44a4f/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_default_plugins
TEST args:  --packages-above rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15214
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22557)](http://ci.ros2.org/job/ci_linux/22557/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16802)](http://ci.ros2.org/job/ci_linux-aarch64/16802/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2073)](http://ci.ros2.org/job/ci_linux-rhel/2073/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23348)](http://ci.ros2.org/job/ci_windows/23348/)

2025-02-18 22:23 UTC, ahcorde approved these changes

2025-02-18 22:23 UTC, merged