Update package maintainer for rviz2
ros2/rviz pull request #365
Opened 2018-11-16 22:58 UTC by cottsay

2018-11-16 23:05 UTC, nuclearsandwich approved these changes

2018-11-17 00:35 UTC, wjwwood approved these changes

2018-11-17 00:36 UTC, wjwwood requested changes
Actually, can you move Deanna's entry into the author tags?

2018-12-07 02:40 UTC, cottsay commented
@wjwwood - ping

2018-12-07 04:23 UTC, wjwwood approved these changes

2018-12-07 04:38 UTC, merged