use image_transport to subscribe to image messages
ros2/rviz pull request #523
Opened 2020-04-01 14:35 UTC by ketatam

ImageDisplay and CameraDisplay now use image_transport to subscribe to image messages, so that it is possible to subscribe to different types of image messages (compressed, theora..).
CameraDisplay also uses image_transport to get the CameraInfoTopic. 
This needs image_common to be added, see corresponding PR: https://github.com/ros2/ros2/pull/884

2020-08-06 18:59 UTC, audrow reviewed
Your changes look good to me. However, this PR depends on [`image_common`](https://github.com/ros-perception/image_common/tree/ros2), which is currently not passing CI ([latest attempt](https://travis-ci.org/github/ros-perception/image_common/builds/601511357)) on the `ros2` branch (the branch mentioned in your other PR: https://github.com/ros2/ros2/pull/884). I would feel better about this new dependency if CI was passing on `image_common`'s `ros2` branch.

2020-08-06 18:59 UTC, audrow commented on rviz_default_plugins/test/rviz_default_plugins/displays/image/get_transport_from_topic_test.cpp
> +
Perhaps you could add [visual tests](https://github.com/ros2/rviz/tree/ros2/rviz_visual_testing_framework) to make sure that different image types are displayed as expected. For example, see [here](https://github.com/ros2/rviz/blob/ros2/rviz_default_plugins/test/rviz_default_plugins/displays/image/image_display_visual_test.cpp).

2020-08-09 09:44 UTC, Martin-Idel commented
@audrow Regarding image_common I agree, this should first be in the general ros2.repos file. However, we need new CI - the latest attempt was 10 months ago. In https://github.com/ros2/ros2/pull/884 there was a different CI attempt, but after that, I put in some effort to fix the CI failures, maybe you could give CI another try?

Regarding visual tests, we discussed this: The problem is that we'd need to publish e.g. compressed images which means we'd need yet another dependency (either opencv or the compressed image publisher) aside from `image_common`. That's when we decided against adding another visual test - note that there is one for general uncompressed images.

2020-08-09 09:44 UTC, Martin-Idel commented on rviz_default_plugins/test/rviz_default_plugins/displays/image/get_transport_from_topic_test.cpp
> +
We discussed this: The problem is that we'd need to publish e.g. compressed images which means we'd need yet another dependency (either opencv or the compressed image publisher) aside from image_common. That's when we decided against adding another visual test - note that there is one for general uncompressed images.

2020-08-10 23:27 UTC, audrow commented
Building for CI failed ([![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11852)](http://ci.ros2.org/job/ci_linux/11852/)) so I've tried rebasing and rerunning CI:  [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11860)](http://ci.ros2.org/job/ci_linux/11860/).

2020-08-13 18:50 UTC, audrow commented
I added the `image_transport` dependency to the `rviz_default_plugins`'s `package.xml`, so that CI will build. 

Here's the new run: 
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11925)](http://ci.ros2.org/job/ci_linux/11925/)

2020-08-14 21:16 UTC, audrow commented
Here's the full CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11945)](http://ci.ros2.org/job/ci_linux/11945/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6990)](http://ci.ros2.org/job/ci_linux-aarch64/6990/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9738)](http://ci.ros2.org/job/ci_osx/9738/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11890)](http://ci.ros2.org/job/ci_windows/11890/)

2020-08-16 18:34 UTC, Martin-Idel requested changes
@audrow Thanks for taking a look. We're probably nearly there.

I don't have push rights to this repository, so I can't simply update this branch. I don't have a Windows machine right here to test, but the problem seems to be just symbol visibility (as always), so this should do the trick.

Also, it's necessary to include the new `.hpp` headers to get rid of warnings (that should fix mac CI).

2020-08-16 18:34 UTC, Martin-Idel commented on rviz_default_plugins/include/rviz_default_plugins/displays/image/image_transport_display.hpp
> +#include "image_transport/subscriber_filter.h"
```suggestion
#include "image_transport/image_transport.hpp"
#include "image_transport/subscriber_filter.hpp"
```

2020-08-16 18:34 UTC, Martin-Idel commented on rviz_default_plugins/src/rviz_default_plugins/displays/camera/camera_display.cpp
> +#include "image_transport/camera_common.h"
```suggestion
#include "image_transport/camera_common.hpp"
```

2020-08-16 18:34 UTC, Martin-Idel commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/get_transport_from_topic.cpp
> +std::string getTransportFromTopic(const std::string & topic)
```suggestion
std::string RVIZ_DEFAULT_PLUGINS_PUBLIC getTransportFromTopic(const std::string & topic)
```

2020-08-16 18:34 UTC, Martin-Idel commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/get_transport_from_topic.cpp
> +#include "rviz_default_plugins/displays/image/get_transport_from_topic.hpp"
```suggestion
#include "rviz_default_plugins/displays/image/get_transport_from_topic.hpp"
#include "rviz_default_plugins/visibility_control.hpp"
```

2020-08-16 18:34 UTC, Martin-Idel commented on rviz_default_plugins/src/rviz_default_plugins/displays/image/get_transport_from_topic.cpp
> +std::string getBaseTopicFromTopic(const std::string & topic)
```suggestion
std::string RVIZ_DEFAULT_PLUGINS_PUBLIC getBaseTopicFromTopic(const std::string & topic)
```

2020-08-17 20:12 UTC, audrow commented
Rerunning after applying changes:
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9754)](http://ci.ros2.org/job/ci_osx/9754/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11908)](http://ci.ros2.org/job/ci_windows/11908/)

2020-08-18 19:24 UTC, Martin-Idel commented
Ouch, my bad. We have to put the macros to the header files, not the `.cpp` files. That should fix it. Sorry about that.

2020-08-18 23:03 UTC, audrow commented
No worries, I should have caught it in reviewing your suggestions. Here's the new Windows run:

Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11937)](http://ci.ros2.org/job/ci_windows/11937/)

2020-08-19 01:54 UTC, audrow commented
I'll run CI once more to make sure all OSs build:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12003)](http://ci.ros2.org/job/ci_linux/12003/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7030)](http://ci.ros2.org/job/ci_linux-aarch64/7030/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9781)](http://ci.ros2.org/job/ci_osx/9781/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11939)](http://ci.ros2.org/job/ci_windows/11939/)

2020-08-25 18:55 UTC, audrow approved these changes
LGTM, after https://github.com/ros2/ros2/pull/884 is merged in.

Maybe @mjcarroll wants to take a look before this is merged in.

2020-12-22 19:27 UTC, Martin-Idel commented
@ketatam https://github.com/ros2/ros2/pull/884 has been merged, do you have some time rebasing this PR and seeing whether it builds? Otherwise I can try to do this over the holidays.

2021-04-19 12:17 UTC, vmanchal1 commented
Any updates on this? When can this be available to use?

2021-05-07 11:34 UTC, Martin-Idel commented
@mjcarroll @audrow

I tested this PR and it still seems to work. Since this is not my repository I cannot merge master into this PR (the conflict is trivial as it's only in the README).

So it should be enough to rebase onto master + new CI for this to get merged. Maybe we can make it happen :).

2021-05-07 16:49 UTC, audrow commented
Thanks for the ping, @Martin-Idel. Here's CI after doing a rebase and fixing the merge conflict:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14585)](http://ci.ros2.org/job/ci_linux/14585/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9340)](http://ci.ros2.org/job/ci_linux-aarch64/9340/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12249)](http://ci.ros2.org/job/ci_osx/12249/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14714)](http://ci.ros2.org/job/ci_windows/14714/)

2021-05-07 19:37 UTC, mjcarroll approved these changes

2021-05-07 19:37 UTC, merged

2021-12-20 12:19 UTC, dwffls commented
Could you show me what the steps would be to implement a compressed image to this visualizer?
Really want to write a PR for this but just don't know where to start.