Don't attempt to moc generate files that don't have QOBJECT.
ros2/rviz pull request #690
Opened 2021-05-14 18:54 UTC by clalancette

This avoids a warning.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This removes a warning seen on Linux that looks like:

```
Note: No relevant classes found. No output generated.
```

for each of the two files.

2021-05-14 18:55 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14643)](http://ci.ros2.org/job/ci_linux/14643/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9396)](http://ci.ros2.org/job/ci_linux-aarch64/9396/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12307)](http://ci.ros2.org/job/ci_osx/12307/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14787)](http://ci.ros2.org/job/ci_windows/14787/)

2021-05-24 16:31 UTC, ahcorde requested changes
do we need a tf2 release https://build.ros2.org/job/Rpr__rviz__ubuntu_focal_amd64/123/console ?

2021-05-24 18:08 UTC, clalancette commented
> do we need a tf2 release https://build.ros2.org/job/Rpr__rviz__ubuntu_focal_amd64/123/console ?

Yeah, I think we do.  I was holding off because of some other stuff going on there (particularly https://github.com/ros2/geometry2/pull/420).

2021-05-24 19:59 UTC, wjwwood approved these changes
lgtm, I don't think you really need to wait for the Rpr job, but it's up to the maintainers.

2021-05-26 14:51 UTC, ahcorde approved these changes

2021-05-26 15:02 UTC, clalancette commented
I'm going to go ahead and merge this, because the failing PR job is not because of this.  Thanks for the reviews!

2021-05-26 15:02 UTC, merged