mass property visualization
ros2/rviz pull request #714
Opened 2021-06-22 17:45 UTC by briansoe66

Add mass properties to robot model display, robot, and robot link.
Visual representation is based on gazebo,
i.e. visualize mass as equivalent lead ball and inertia as box, located at center of mass.

2021-06-22 17:46 UTC, briansoe66 commented
This pull request will resolve https://github.com/ros-visualization/rviz/issues/1204

2021-06-22 17:58 UTC, briansoe66 commented
Could someone independently verify that the mass and inertia visualization shapes match gazebo, for the UR model? Note: The color will not match.

2021-07-13 12:24 UTC, ahcorde approved these changes
I already tested it with some models and it looks good!

2021-07-13 12:27 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14875)](http://ci.ros2.org/job/ci_linux/14875/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9625)](http://ci.ros2.org/job/ci_linux-aarch64/9625/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12542)](http://ci.ros2.org/job/ci_osx/12542/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15035)](http://ci.ros2.org/job/ci_windows/15035/)

2021-07-13 13:47 UTC, ahcorde requested changes
Windows is failing:

```
15:39:05 C:\ci\ws\src\ros2\rviz\rviz_default_plugins\src\rviz_default_plugins\robot\robot_link.cpp(833,65): error C2065: 'M_PI': undeclared identifier [C:\ci\ws\build\rviz_default_plugins\rviz_default_plugins.vcxproj]
```

2021-07-13 15:57 UTC, mjeronimo approved these changes

2021-07-14 07:44 UTC, ahcorde commented
Hi @briansoe66 ,

do you think you will have some time to fix this ?

2021-07-16 05:07 UTC, briansoe66 commented
> Hi @briansoe66 ,
> 
> do you think you will have some time to fix this ?

@ahcorde , I have committed a fix for the undefined M_PI on windows, but I have no windows computer to verify it worked.

2021-07-16 07:36 UTC, ahcorde commented
thnk you @briansoe66, let's try again

* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15051)](http://ci.ros2.org/job/ci_windows/15051/)

2021-07-19 12:38 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14904)](http://ci.ros2.org/job/ci_linux/14904/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9647)](http://ci.ros2.org/job/ci_linux-aarch64/9647/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12573)](http://ci.ros2.org/job/ci_osx/12573/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15060)](http://ci.ros2.org/job/ci_windows/15060/)

2021-07-19 12:38 UTC, ahcorde approved these changes
LGTM with green CI

2021-07-19 15:33 UTC, merged

2021-07-19 22:33 UTC, Garrus007 commented
@briansoe66, appreciate your work, thanks!

2021-11-03 01:54 UTC, jose-adrian commented
Can someone please explain how to get this to work?

2021-11-03 08:41 UTC, ahcorde commented
@jose-adrian, if you want to visualize the mass, you should include the plugin `RobotModel`and configure it, Then you should click in `mass Properties -> Mass`. Like in this small gif

![mass_rviz](https://user-images.githubusercontent.com/1933907/140030252-e1734761-9872-45dc-9b5e-f5ba1fd52331.gif)

Anyhow please ask this kind of questions in https://answers.ros.org/questions/

2021-11-03 11:18 UTC, jose-adrian commented
Thanks for the answer! The problem is that I can't get those Mass Properties check boxes to appear in the RobotModel. Sorry to ask here but no luck in the ros forums, anyhow, I'll try again. Thanks!