Fix for ogre failing when material already exists
ros2/rviz pull request #729
Opened 2021-07-20 10:30 UTC by wolfv

This came up in the RoboStack project where we're using a more recent OGRE

2021-07-20 10:32 UTC, wolfv commented
For more context: https://medium.com/robostack/cross-platform-conda-packages-for-ros-fa1974fd1de3

And here we're working towards a full galactic build: https://github.com/robostack/ros-galactic

2021-07-20 10:58 UTC, ahcorde requested changes

2021-07-20 10:58 UTC, ahcorde commented on rviz_rendering/src/rviz_rendering/material_manager.cpp
> +  std::dynamic_pointer_cast<Ogre::Material>(retrieve_result.first)->setLightingEnabled(false);
```suggestion
   auto material = std::dynamic_pointer_cast<Ogre::Material>(retrieve_result.first);
   if (material) {
     material->setLightingEnabled(false);
   }
```

2021-07-20 12:12 UTC, wolfv commented
I am fine with this change although it should generally never happen (I suppose) since the resource will either be created or retrieved.

2021-07-20 12:18 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14909)](http://ci.ros2.org/job/ci_linux/14909/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9652)](http://ci.ros2.org/job/ci_linux-aarch64/9652/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12580)](http://ci.ros2.org/job/ci_osx/12580/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15067)](http://ci.ros2.org/job/ci_windows/15067/)

2021-07-20 20:11 UTC, ahcorde requested changes
uncrustify is failing https://build.ros2.org/job/Rpr__rviz__ubuntu_focal_amd64/174/

2021-08-10 16:39 UTC, ahcorde commented
friendly ping @wolfv

2021-08-11 06:32 UTC, wolfv commented
I was on vacation :) fixed now!

2021-08-16 14:56 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15055)](http://ci.ros2.org/job/ci_linux/15055/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9789)](http://ci.ros2.org/job/ci_linux-aarch64/9789/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12742)](http://ci.ros2.org/job/ci_osx/12742/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15223)](http://ci.ros2.org/job/ci_windows/15223/)

2021-08-17 08:21 UTC, merged

2021-08-17 08:23 UTC, ahcorde commented
@wolfv do you need to backport this ?