TF2 buffer cache time option
ros2/rviz pull request #780
Opened 2021-10-05 21:07 UTC by gonzodepedro

Signed-off-by: Gonzalo de Pedro <gonzalo@depedro.com.ar>

2021-10-06 16:54 UTC, ahcorde requested changes
Linters are failing

2021-11-02 21:51 UTC, jacobperron reviewed
This seems like a fairly invasive change for a CLI option; it touches API in a lot of places.

What if we declared a read-only parameter on the node after parsing the argument, and then the TFWrapper can access the value through the node instead?

2021-11-03 15:09 UTC, ivanpauno commented
Agreed, see https://github.com/ros2/rviz/pull/792

2021-11-03 20:14 UTC, ivanpauno commented
Replaced with https://github.com/ros2/rviz/pull/792

2021-11-03 20:14 UTC, closed without merging