export image_transport dependency
ros2/rviz pull request #813
Opened 2021-12-28 03:10 UTC by iuhilnehc-ynos

When I build the `nav2_rviz_plugins` package which depends on `rviz_default_plugins`, it failed as follows,

```
--- stderr: nav2_rviz_plugins                                                                                                       
CMake Error at CMakeLists.txt:50 (add_library):
  Target "nav2_rviz_plugins" links to target
  "image_transport::image_transport" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
```

I think it's better to use `ament_export_dependencies` for the `image_transport` rather than add the find_package(image_transport) in `nav2_rviz_plugins`.

Signed-off-by: Chen Lihui <lihui.chen@sony.com>

2021-12-28 07:41 UTC, aprotyas approved these changes

2021-12-31 16:09 UTC, clalancette requested changes

2021-12-31 16:09 UTC, clalancette commented on rviz_default_plugins/CMakeLists.txt
> +  image_transport
Can you please put it in alphabetical order in the list?  Also we should do the same for the `ament_target_dependencies` above.

2022-01-02 16:20 UTC, clalancette approved these changes
Looks good with green CI.

2022-01-04 03:19 UTC, iuhilnehc-ynos commented
CI:
Build args: `--packages-above-and-dependencies rviz_default_plugins`
Test args: `--packages-above rviz_default_plugins`
 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15881)](http://ci.ros2.org/job/ci_linux/15881/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10558)](http://ci.ros2.org/job/ci_linux-aarch64/10558/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13547)](http://ci.ros2.org/job/ci_osx/13547/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=16184)](http://ci.ros2.org/job/ci_windows/16184/)

2022-01-04 16:44 UTC, merged