Fixes policy CMP0135 warning for CMake >= 3.24
ros2/rviz pull request #898
Opened 2022-09-09 20:08 UTC by Crola1702

Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>

Reference build: https://ci.ros2.org/view/nightly/job/nightly_win_deb/2473/

[This](https://cmake.org/cmake/help/latest/policy/CMP0135.html) warning started appearing on new windows machines. It’s caused by a new CMake version (3.24) that expects this policy to be set.

This PR sets CMP0135 policy in `CMakeLists.txt`

CI launch:
* Linux [![Build Status](https://ci.ros2.org/job/ci_linux/17254/badge/icon)](https://ci.ros2.org/job/ci_linux/17254/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11793)](http://ci.ros2.org/job/ci_linux-aarch64/11793/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17734)](http://ci.ros2.org/job/ci_windows/17734/)

2022-09-09 20:09 UTC, clalancette approved these changes

2022-09-12 13:53 UTC, Blast545 requested changes
LGTM, @Crola1702 please take a look to the linter errors before merging. Those are related to your changes.

2022-09-12 14:10 UTC, clalancette requested changes
Also, let's change this to NEW policy to match what we are doing elsewhere.

2022-09-12 14:28 UTC, Crola1702 commented
New CI_launcher builds with fixes and new behaviour:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17271)](http://ci.ros2.org/job/ci_linux/17271/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11812)](http://ci.ros2.org/job/ci_linux-aarch64/11812/)
* Windows [![Build Status](https://ci.ros2.org/job/ci_windows/17753/badge/icon)](https://ci.ros2.org/job/ci_windows/17753/)

2022-09-12 14:33 UTC, clalancette approved these changes

2022-09-12 15:44 UTC, Blast545 approved these changes

2022-09-12 15:48 UTC, merged

2023-01-03 12:33 UTC, Crola1702 commented
@Mergifyio backport humble