Fix MeshResourceMarker for mesh with color-based embedded material
ros2/rviz pull request #928
Opened 2022-11-25 08:12 UTC by xbroquer

Issue: Color from embedded color based mesh are overrided and not rendered as expected

It was an known issue on ROS1 that was fixed by
https://github.com/ros-visualization/rviz/pull/1424

Kudos to the original author

Fix #927

Signed-off-by: Xavier BROQUERE <xav.broquere@gmail.com>

2022-11-25 08:27 UTC, xbroquer commented
In order to test this PR , I used this repo https://github.com/xbroquer/rviz_collada_marker/tree/ros2
ros2 launch rviz_collada_marker mesh_marker_test.launch.py

| Humble            |  PR tested on Humble |
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-25 09-07-49](https://user-images.githubusercontent.com/3864052/203934952-b5dbc123-e4ec-4cc7-a9b5-16e5bac8c0be.png) | ![Screenshot from 2022-11-25 09-04-02](https://user-images.githubusercontent.com/3864052/203934986-00240e7e-dac5-4f09-a330-6c5825e77f4e.png)

2022-12-07 12:47 UTC, xbroquer commented
Hello @ahcorde, 

 is it possible to review this PR ?  it will be great if this could be in the coming  humble sync :)

Thanks!

2022-12-22 15:58 UTC, clalancette approved these changes

2022-12-22 16:00 UTC, clalancette requested changes
Style fixes needed.  Once those are done, we can run CI on it.

2022-12-22 16:00 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/mesh_resource_marker.cpp
> +      {
Actually, CI is complaining about the style here.  This should be:

```suggestion
      if (tinting) {
```

2022-12-22 16:00 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/mesh_resource_marker.cpp
> +      {
```suggestion
      } else {
```

2023-01-02 14:22 UTC, clalancette approved these changes

2023-01-02 14:24 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17869)](http://ci.ros2.org/job/ci_linux/17869/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12437)](http://ci.ros2.org/job/ci_linux-aarch64/12437/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18542)](http://ci.ros2.org/job/ci_windows/18542/)

2023-01-02 16:32 UTC, merged

2023-03-26 20:03 UTC, xbroquer commented
Hi  @clalancette ,
Is it possible to backport this change on humble ? Do I have to do something ?

Thanks

2023-03-27 13:38 UTC, clalancette commented
> Is it possible to backport this change on humble ?

It looks like it preserves ABI and API, so yes, we can backport it.  I'll ask the bot to do it.

2023-03-27 13:38 UTC, clalancette commented
@Mergifyio backport humble