Update Frame shortcut
ros2/rviz pull request #958
Opened 2023-03-17 13:44 UTC by DLu

2023-03-17 19:27 UTC, clalancette reviewed
Just so I understand; this changes no logic, but just consolidates some duplicated lines of code into a method.  Is that correct?

2023-03-17 20:58 UTC, DLu commented
Correct

2023-03-20 13:32 UTC, clalancette requested changes
I've left one style nit to fix, otherwise this looks good to me.

2023-03-20 13:32 UTC, clalancette commented on rviz_common/include/rviz_common/display.hpp
> +  bool updateFrame(const std::string& frame);
```suggestion
  bool updateFrame(const std::string & frame);
```

2023-03-20 14:22 UTC, clalancette approved these changes

2023-03-20 14:23 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18263)](http://ci.ros2.org/job/ci_linux/18263/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12799)](http://ci.ros2.org/job/ci_linux-aarch64/12799/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18940)](http://ci.ros2.org/job/ci_windows/18940/)

2023-03-20 16:54 UTC, merged

2023-03-20 17:09 UTC, DLu commented
Backport to foxy/humble?

2023-03-20 17:11 UTC, clalancette commented
> Backport to foxy/humble?

I think we could; it doesn't really change API/ABI.  On the other hand, it seems like a simple cleanup, so I'm not sure it is worth it.  What's your interest in the backport?

2023-03-20 17:30 UTC, DLu commented
Cleaning up [my new tutorial](https://github.com/ros2/ros2_documentation/pull/3384/files#diff-9fd71dd84295290656bf218e71ff024d71efdf0cfceadffc44370eb153cb20a2R233)

2023-03-20 18:10 UTC, clalancette commented
I'll open up the backport to Humble, though I want to have some soak time in Rolling/Iron before we merge this in.

I'm less inclined to do it for Foxy since we are so close to its EOL.

2023-03-20 18:10 UTC, clalancette commented
@Mergifyio backport humble

2023-03-21 15:20 UTC, DLu commented
Thanks @clalancette ! Thanks @mergifyio!