remove unused code
ros2/rviz pull request #979
Opened 2023-05-09 09:48 UTC by mosfet80

remove unused code

2023-05-09 10:22 UTC, ahcorde approved these changes

2023-05-09 10:24 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18706)](http://ci.ros2.org/job/ci_linux/18706/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13232)](http://ci.ros2.org/job/ci_linux-aarch64/13232/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19438)](http://ci.ros2.org/job/ci_windows/19438/)

2023-05-09 15:49 UTC, clalancette requested changes

2023-05-09 15:49 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/pointcloud/point_cloud_to_point_cloud2.cpp
> -  auto floatData = reinterpret_cast<float *>(output->data.data());
This is not unused code; it is editing the output array.  The same goes for all of the blocks below.

2023-05-11 07:36 UTC, ahcorde requested changes
See the comment, I think you can close this PR https://github.com/ros2/rviz/pull/979/files/e2c5b40454fb4c3d49f778b676f9a80a5952e39b#r1188808624

2023-05-11 08:15 UTC, closed without merging