uniform cmake_minimum and C++XX
ros2/rviz pull request #982
Opened 2023-05-10 22:32 UTC by mosfet80

Some rviz subprojects require cmake_min 3.5 and some 3.10. I've standardized the minimum requirement of rviz to 3.10.
Some subprojects require c++14 and some require c++17. ros rolling requires c++17 -> i set rviz with build requirement to c++17

2023-05-11 07:35 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18710)](http://ci.ros2.org/job/ci_linux/18710/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13236)](http://ci.ros2.org/job/ci_linux-aarch64/13236/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19442)](http://ci.ros2.org/job/ci_windows/19442/)

2023-05-11 12:29 UTC, clalancette commented
Oof, it looks like we have new warnings on Windows with this.  Probably some work needs to be done in `rviz_rendering` or `rviz_rendering_tests` to fix those.

2023-06-01 13:55 UTC, clalancette requested changes

2023-06-01 13:55 UTC, clalancette commented on rviz_rendering/CMakeLists.txt
> +  #pragma warning(suppress : 4008)
I'll note that these `#pragma` don't belong in the `CMakeLists.txt`.  Instead, they typically go into the C++ or header files.

That said, the fact that these are being introduced at all gives me pause.  Why do we need them?

2023-10-04 16:05 UTC, closed without merging