Modify access specifier to protected or public for the scope of processMessage() member function
ros2/rviz pull request #984
Opened 2023-05-12 02:36 UTC by hyunseok-yang

- pose_display, pose_with_covariance_display and relative_humidity_display

2023-05-15 15:48 UTC, clalancette commented on rviz_default_plugins/include/rviz_default_plugins/displays/relative_humidity/relative_humidity_display.hpp
> +protected:
By switching this to `protected`, you are also making `setInitialValues` and `hideUnneededProperties` available to sub-classes.  Do we really need that?

2023-05-16 08:38 UTC, hyunseok-yang commented on rviz_default_plugins/include/rviz_default_plugins/displays/relative_humidity/relative_humidity_display.hpp
> +protected:
Hi,
well I just modified those for consistency of display pluging template.
I didn't mean to make visible to sub-classes but I think that's not a big deal.

And these functions are also virtual function of parent's so that another sub-classese can override that functions.
(although not necessary to me frankly :) )

So, unless it is public, it would be NO problem.

```c++
  void setInitialValues() override;
  void hideUnneededProperties() override;
```

2023-05-16 14:49 UTC, clalancette commented on rviz_default_plugins/include/rviz_default_plugins/displays/relative_humidity/relative_humidity_display.hpp
> +protected:
> And these functions are also virtual function of parent's so that another sub-classese can override that functions.

Right, but these are the derived classes, not the base class.

I guess I'll say that in every single other class that derives from `PointCloudScalarDisplay`, these two methods are private.  So I'd prefer to keep that consistent here, and leave these methods private.

2023-05-16 15:16 UTC, hyunseok-yang commented on rviz_default_plugins/include/rviz_default_plugins/displays/relative_humidity/relative_humidity_display.hpp
> +protected:
To me, all I need is override `processMessage()` function.  So it's fine to keep two methods as a private functions.

BTW, is it correct that you mentioned?

https://github.com/ros2/rviz/blob/bc93b3488e9b204b1e0e9df2455e1c66c552cb41/rviz_default_plugins/include/rviz_default_plugins/displays/pointcloud/point_cloud_scalar_display.hpp#L97

Cause you said those are 'private' but it written as a protected :)

2023-05-16 15:17 UTC, hyunseok-yang commented on rviz_default_plugins/include/rviz_default_plugins/displays/relative_humidity/relative_humidity_display.hpp
> +protected:
> > And these functions are also virtual function of parent's so that another sub-classese can override that functions.
> 
> Right, but these are the derived classes, not the base class.
> 
> I guess I'll say that in every single other class that derives from `PointCloudScalarDisplay`, these two methods are private. So I'd prefer to keep that consistent here, and leave these methods private.

To me, all I need is override `processMessage()` function.  So it's fine to keep two methods as a private functions.

BTW, is it correct that you mentioned?

https://github.com/ros2/rviz/blob/bc93b3488e9b204b1e0e9df2455e1c66c552cb41/rviz_default_plugins/include/rviz_default_plugins/displays/pointcloud/point_cloud_scalar_display.hpp#L97

Cause you said those are 'private' but it written as a protected :)

2023-05-16 16:57 UTC, clalancette commented on rviz_default_plugins/include/rviz_default_plugins/displays/relative_humidity/relative_humidity_display.hpp
> +protected:
> Cause you said those are 'private' but it written as a protected :)

I meant `private`.  `setInitialValues` and `hideUnneededProperties` are private in every class that derives from `PointCloudScalarDisplay`, as far as I can tell.

2023-05-17 09:57 UTC, hyunseok-yang commented
@ahcorde @clalancette  I rebased the branch on latest rolling. And fixed all related to access specifier for 'processMessage()' function.

2023-05-17 12:01 UTC, clalancette requested changes

2023-05-17 12:01 UTC, clalancette commented on rviz_default_plugins/include/rviz_default_plugins/displays/fluid_pressure/fluid_pressure_display.hpp
> +class RVIZ_DEFAULT_PLUGINS_PUBLIC z
This is a typo.

```suggestion
class RVIZ_DEFAULT_PLUGINS_PUBLIC FluidPressureDisplay
```

2023-05-17 14:25 UTC, hyunseok-yang reviewed
d'oh
thanks

2023-05-17 14:25 UTC, hyunseok-yang commented on rviz_default_plugins/include/rviz_default_plugins/displays/relative_humidity/relative_humidity_display.hpp
> +protected:
> > Cause you said those are 'private' but it written as a protected :)
> 
> I meant `private`. `setInitialValues` and `hideUnneededProperties` are private in every class that derives from `PointCloudScalarDisplay`, as far as I can tell.

I see, now I get it. I didn't check another class such as `FluidPressureDisplay` which is derivied from PointCloudScalarDisplay`

2023-05-17 14:25 UTC, hyunseok-yang commented on rviz_default_plugins/include/rviz_default_plugins/displays/relative_humidity/relative_humidity_display.hpp
> +protected:
I will modify it to 'private' for consistency in terms of what you mentioned above.

And will modify more plugins for `processMessage()` function.

2023-05-17 14:27 UTC, clalancette approved these changes
Thanks for iterating.  This looks good to me; I'll run CI on it next.

2023-05-17 14:28 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18757)](http://ci.ros2.org/job/ci_linux/18757/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13282)](http://ci.ros2.org/job/ci_linux-aarch64/13282/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19500)](http://ci.ros2.org/job/ci_windows/19500/)

2023-05-17 16:55 UTC, merged

2023-05-18 11:24 UTC, hyunseok-yang commented
@clalancette 
Hi, Could you let me know when this changes can merged into humble branch?
I just wonder how the CI/CID process works :)

2023-05-18 12:38 UTC, clalancette commented
> Hi, Could you let me know when this changes can merged into humble branch?

We have to consider further before backporting to humble.  In particular, we have to be sure these changes don't change ABI.  I don't *think* that they do, but I need to consider it further.

2023-05-18 13:42 UTC, hyunseok-yang commented
> 

OK. Thanks for your comment.
Have a good day

2023-06-06 14:28 UTC, clalancette commented
Unfortunately, looking at this closer, it looks like this has the potential to change ABI.  In particular, see https://community.kde.org/Policies/Binary_Compatibility_Examples#Change_the_access_rights .  So we cannot backport this to `humble` as-is.

That said, there is a workaround mentioned in https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B (search for "Changing the access rights").  In particular, you could make a new `protected` method that called the existing `private` method.  If you'd like to pursue that path, I'm happy to review the resulting PR.

2023-06-07 13:30 UTC, hyunseok-yang commented
> Unfortunately, looking at this closer, it looks like this has the potential to change ABI. In particular, see https://community.kde.org/Policies/Binary_Compatibility_Examples#Change_the_access_rights . So we cannot backport this to `humble` as-is.
> 
> That said, there is a workaround mentioned in https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B (search for "Changing the access rights"). In particular, you could make a new `protected` method that called the existing `private` method. If you'd like to pursue that path, I'm happy to review the resulting PR.

Thanks for your review.
Understood in terms of 'changing the access rights'.

I'd like to make a new `protected` method which calls existing `private` function. I'm not sure this path makes consistency with other class. 
And then, most important things is `processMessage()` function is called by somewhere else as a binding function. So it's not easy to implement what I expected.

I think workaround solution for just humble is not a way of good design.


Is there any other option to backport into humble? :(

2023-06-07 13:40 UTC, clalancette commented
> Is there any other option to backport into humble? :(

Unfortunately no.  We have to keep ABI in humble.