Added Effort plugin
ros2/rviz pull request #990
Opened 2023-06-07 13:13 UTC by ahcorde

Added Effort plugin

![effort_plugin](https://github.com/ros2/rviz/assets/1933907/fee13f9b-682a-4a40-8371-c9003208f4dd)

2023-06-07 18:41 UTC, clalancette requested changes
First pass review.

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/include/rviz_default_plugins/displays/effort/effort_display.hpp
> +// class EffortVisual;
I think we should delete these commented-out lines.

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/include/rviz_default_plugins/displays/effort/effort_display.hpp
> +//   // Helper function to apply color and alpha to all visuals.
```suggestion
  // Helper function to apply color and alpha to all visuals.
```

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/plugins_description.xml
> +      The Effort display shows a sensor_msgs/JointState/effort message as circled arrows around each revolute joint in the robot. &lt;a href="http://www.ros.org/wiki/rviz/DisplayTypes/Effort"&gt;More
I know we have the links to the wiki elsewhere in this file, but I don't think we should add in more.  The wiki will (eventually) go away.

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +  joints_.insert(std::make_pair(joint, info));
I think you need `#include <utility>` at the top of the file for `std::make_pair`.

More importantly, what is responsible for freeing the `info` pointer here?

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +      joints_[joint_name] = createJoint(joint_name);
It seems a little weird to me that `createJoint` is inserting the object into `joints_`, but then we are doing it again here.  Do we need to do that twice?

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +{
```suggestion
}

void JointInfo::setMaxEffort(double m)
{
```

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +    "Width", 0.02, "Width to drow effort circle", this,
```suggestion
    "Width", 0.02, "Width to draw effort circle", this,
```

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +    "Scale", 1.0, "Scale to drow effort circle", this,
```suggestion
    "Scale", 1.0, "Scale to draw effort circle", this,
```

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +    "description.",
```suggestion
    "Name of the topic from which to load the robot "
    "description.",
```

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +  // joints_category_);
Just delete this commented-out code.

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +void EffortDisplay::processMessage(sensor_msgs::msg::JointState::ConstSharedPtr msg)
Need to `#include <sensor_msgs/msg/joint_state.hpp>` at the top of the file for this.

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +    std::cerr << "Robot model might not be loaded already" << '\n';
```suggestion
  // Robot model might not be loaded yet
  if (!robot_model_) {
    std::cerr << "Robot model might not be loaded yet" << '\n';
```

Besides this, an unconditional print here seems problematic.  It seems like 1) the user might miss this on the console, and 2) we might spam the user early on with a lot of these messages.  Could we instead update the Status field somehow?

2023-06-07 18:41 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +          "Array Topic",
Do you know what "Array Topic" refers to here?

2023-06-07 18:41 UTC, clalancette commented on rviz_rendering/src/rviz_rendering/objects/effort_visual.cpp
> +  value = std::max(value, 0.0f);
I think you need `#include <algorithm>` at the top of the file for this.

2023-06-07 18:41 UTC, clalancette commented on rviz_rendering/src/rviz_rendering/objects/effort_visual.cpp
> +  int i = floor(h);
I think you need `#include <cmath>` at the top of the file for this.

2023-06-07 18:41 UTC, clalancette commented on rviz_rendering/test/rviz_rendering/objects/effort_visual_test.cpp
> +// #include <OgreManualObject.h>
Remove this commented-out code.

2023-06-07 18:41 UTC, clalancette commented on rviz_rendering/test/rviz_rendering/objects/effort_visual_test.cpp
> +//
Remove this commented-out code.

2023-06-07 18:41 UTC, clalancette commented on rviz_rendering/test/rviz_rendering/objects/effort_visual_test.cpp
> +  std::shared_ptr<rviz_rendering::OgreTestingEnvironment> testing_environment_;
Add `#include <memory>` at the top of the file.

2023-06-07 18:41 UTC, clalancette commented on rviz_rendering/test/rviz_rendering/objects/effort_visual_test.cpp
> +  std::cerr << "here" << '\n';
Add `#include <iostream>` at the top of the file.

2023-06-14 16:39 UTC, clalancette requested changes
I left a few more comments; these all should be pretty easy to fix.  Once that is done I'm happy with this.

2023-06-14 16:39 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +      joints_[joint_name] = createJoint(joint_name);
At this point, `createJoint` is a one-liner, so I'll suggest we just inline it here:

```suggestion
      joints_[joint_name] = new JointInfo(joint_name, joints_category_);
```

and remove the the `createJoint` method.

2023-06-14 16:39 UTC, clalancette commented on rviz_default_plugins/include/rviz_default_plugins/displays/effort/effort_display.hpp
> +  typedef std::map<std::string, JointInfo *> M_JointInfo;
I just had a thought about this.  If we instead made this:

```suggestion
  typedef std::map<std::string, std::unique_ptr<JointInfo>> M_JointInfo;
```

Then we wouldn't need to explicitly free it in the destructor.  We'd also have to change where we allocate it to `std::make_unique`, but I think that is probably worth it.

2023-06-14 16:39 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +    // ROS_ERROR("Unable to parse URDF description!");
Remove this commented-out code.

2023-06-14 16:39 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +  // Robot model might not be loaded already
```suggestion
  // Robot model might not be loaded yet
```

2023-06-14 16:39 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +    std::cerr << "Robot model might not be loaded yet" << '\n';
My previous comment about this still seems to be open:

"an unconditional print here seems problematic. It seems like 1) the user might miss this on the console, and 2) we might spam the user early on with a lot of these messages. Could we instead update the Status field somehow?"

(though maybe this isn't possible)

2023-06-14 16:39 UTC, clalancette commented on rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp
> +    visual.reset(new rviz_rendering::EffortVisual(context_->getSceneManager(), scene_node_));
I think `std::make_shared` is generally preferred for memory layout and other reasons:

```suggestion
    visual = std::make_shared<rviz_rendering::EffortVisual>(context_->getSceneManager(), scene_node_);
```

2023-06-19 09:04 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18993)](http://ci.ros2.org/job/ci_linux/18993/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13517)](http://ci.ros2.org/job/ci_linux-aarch64/13517/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19736)](http://ci.ros2.org/job/ci_windows/19736/)

2023-06-19 11:17 UTC, ahcorde commented
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19738)](http://ci.ros2.org/job/ci_windows/19738/)

2023-06-20 09:25 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18997)](http://ci.ros2.org/job/ci_linux/18997/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13521)](http://ci.ros2.org/job/ci_linux-aarch64/13521/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19748)](http://ci.ros2.org/job/ci_windows/19748/)

2023-06-20 13:51 UTC, clalancette commented
So the code here is looking good to me.

The thing I'm wondering about is whether we should actually add this to the default set of RViz plugins.  That is, we already have a large set, and it already takes quite a long time to compile this package.  Is this plugin important/universal enough that we should include it in the default set, or can we distribute it in a separate package instead?

2023-06-21 10:10 UTC, ahcorde commented
> So the code here is looking good to me.
> 
> The thing I'm wondering about is whether we should actually add this to the default set of RViz plugins. That is, we already have a large set, and it already takes quite a long time to compile this package. Is this plugin important/universal enough that we should include it in the default set, or can we distribute it in a separate package instead?

@clalancette I can add here two arguments:

 - **Out of the box experience**: When people are trying to migrate from ROS 1 to ROS 2, they will expect to have the same behaviour without any additional step.
 - **Feature parity**: With these 3 open PRs we will reach feature parity (finally).

2023-06-26 14:46 UTC, ahcorde commented
friendly ping @clalancette

2023-06-26 19:27 UTC, clalancette commented
So here is the issue that I'm struggling with this.

First, we've gone many years without these plugins, and haven't had a lot of call for them.  That doesn't mean there has been zero call for them, or that they don't have value, but these PRs are the first time I've heard of them requested.  That makes me think that they aren't necessarily widely used, and hence could be in a separate package.  That would also make it so that these plugins aren't release-critical, and thus keep from adding additional burden on the core maintainers.

Second, our build and test times are already absurd.  Here are some numbers:

* On Linux, it currently takes us 2 hours and 26 minutes to run a [nightly](https://ci.ros2.org/view/nightly/job/nightly_linux_release/2702/) full build and test.  Of that, 59 minutes are spent compiling.  And of that, the largest compile time is for `rviz_default_plugins` at 11 minutes.
* On Windows, the situation is far more dire.  It currently takes us 5 hours and 44 minutes to run a [nightly](https://ci.ros2.org/view/nightly/job/nightly_win_rel/2722/) full build and test.  Of that, 2 hours 45 minutes are spent compiling.  And of that, the largest compile time is for `rviz_default_plugins` at 32 minutes.

This combination of factors makes me think that these plugins should be released into a separate package for manipulation.  Maybe `rviz_manipulation_plugins` or something like that.  It could then be released into humble, iron, and rolling, and be available as normal.

All of that said, I could be convinced otherwise.  I'd also like to hear from @ros2/team here for other opinions.

2023-06-26 20:53 UTC, sloretz commented
> [...] And of that, the largest compile time is for rviz_default_plugins at 32 minutes.

I agree `rviz_default_plugins` is really slow to build. By how much does adding this plugin increase the compile time? If it increases it significantly then I'd see that as justification to put it in a different package.

2023-06-29 10:19 UTC, ahcorde commented
I created this branch `ahcorde/rolling/rviz_default_plugins_parity` which includes the remaining rviz default plugins to get the feature parity. Let's see how much increase the compilation time.

* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19791)](http://ci.ros2.org/job/ci_windows/19791/)

2023-06-30 10:33 UTC, ahcorde commented
@clalancette in this last build the time to compile rviz_default_plugins with these three new plugins is 

```bash
Finished <<< rviz_default_plugins [22min 55s]
```

What do you think?  can we move forward ?

2023-07-05 19:35 UTC, clalancette commented
> What do you think? can we move forward ?

Looking at the build time in your example branch, it is actually substantially less than the current nightly CI times ([22 minutes for your CI](https://ci.ros2.org/job/ci_windows/19796/consoleFull) vs [32 minutes for nightly CI](https://ci.ros2.org/view/nightly/job/nightly_win_rel/2731/consoleFull), and they were running on the same AWS instance).  That seems counter-intuitive; we are adding code, so it should be at least the same amount of time, if not longer.  Do you have any idea why that might be?

2023-07-05 20:52 UTC, ahcorde commented
> > What do you think? can we move forward ?
> 
> Looking at the build time in your example branch, it is actually substantially less than the current nightly CI times ([22 minutes for your CI](https://ci.ros2.org/job/ci_windows/19796/consoleFull) vs [32 minutes for nightly CI](https://ci.ros2.org/view/nightly/job/nightly_win_rel/2731/consoleFull), and they were running on the same AWS instance). That seems counter-intuitive; we are adding code, so it should be at least the same amount of time, if not longer. Do you have any idea why that might be?

I don´t have a answer for this, but maybe @j-rivero or @nuclearsandwich have one.

2023-07-07 09:00 UTC, ahcorde commented
I was discussing this with @j-rivero offline, and these are his thoughts:

 - we need to check if both build are running with the same paremeters
 - changes in the `CMakeLists.txt` seems trivial, he can not explain any reduction in time.
 - There are failing test in CI but I think that are all related to linting. If there is a test failure in something time-consuming that could explain why the CI is running in less time but does not seem to be the case.

Last comment is not relevant because we are just comparing compilation times. I will check that the parameters are the same.

2023-07-07 09:04 UTC, ahcorde commented
The only difference is the `CI_CMAKE_BUILD_TYPE` which is setted to `Release`. Launching again the job

* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19839)](http://ci.ros2.org/job/ci_windows/19839/)

2023-07-07 16:12 UTC, nuclearsandwich commented
> I don´t have a answer for this, but maybe @j-rivero or @nuclearsandwich have one.

One thing that jumps out at me is the scoped build argument in the CI job

```
 build_args: --event-handlers console_cohesion+ console_package_list+ --cmake-args -DINSTALL_EXAMPLES=OFF -DSECURITY=ON -DAPPEND_PROJECT_NAME_TO_INCLUDEDIR=ON --packages-above-and-dependencies rviz_default_plugins rviz_rendering rviz_common, 
```

With fewer packages being built there's probably more capacity for the rviz_default_plugins build. To get a true apples-to-apples comparison you would need to build the same set of packages as we do in the nightlies.

2023-07-10 12:34 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19114)](http://ci.ros2.org/job/ci_linux/19114/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13637)](http://ci.ros2.org/job/ci_linux-aarch64/13637/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19857)](http://ci.ros2.org/job/ci_windows/19857/)

2023-07-10 18:50 UTC, clalancette requested changes
I've left two small things to fix, then I think I'm happy with this.

2023-07-10 18:50 UTC, clalancette commented on rviz_default_plugins/CMakeLists.txt
> +  endif()
With the latest changes to the CMakeLists.txt, some of this isn't needed anymore:

```suggestion
  ament_add_gtest(effort_display_visual_test
    test/rviz_default_plugins/displays/effort/effort_display_visual_test.cpp
    test/rviz_default_plugins/publishers/effort_publisher.hpp
    test/rviz_default_plugins/page_objects/effort_display_page_object.cpp
    ${SKIP_VISUAL_TESTS}
    TIMEOUT 180)
  if(TARGET effort_display_visual_test)
    target_include_directories(effort_display_visual_test PRIVATE test)
    target_link_libraries(effort_display_visual_test
      rviz_visual_testing_framework::rviz_visual_testing_framework
      rclcpp::rclcpp
      ${sensor_msgs_TARGETS}
    )
  endif()
```

2023-07-10 18:50 UTC, clalancette commented on rviz_default_plugins/test/rviz_default_plugins/publishers/effort_publisher.hpp
> +using namespace std::chrono_literals; //NOLINT
```suggestion
using namespace std::chrono_literals;  // NOLINT
```

2023-07-11 07:35 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19135)](http://ci.ros2.org/job/ci_linux/19135/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13694)](http://ci.ros2.org/job/ci_linux-aarch64/13694/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19870)](http://ci.ros2.org/job/ci_windows/19870/)

2023-07-11 12:45 UTC, clalancette approved these changes

2023-07-11 12:45 UTC, merged

2023-07-13 13:32 UTC, ahcorde commented
https://github.com/Mergifyio backport humble iron

2025-09-08 22:21 UTC, zimmerman-pliant commented
Should this work with continuous joints? I've got an application with a continuous rotary joint where effort display could be useful, but the plugin description mentions `revolute` in particular:

https://github.com/ros2/rviz/blob/rolling/rviz_default_plugins/plugins_description.xml#L66

Edit: swapped my joint to `revolute` temporarily in my URDF and got a working visualization, so empirically I guess it only works with `revolute` joints.